ctx.rule(u'START',u'{PROGRAM}')

ctx.rule(u'PROGRAM',u'{ELEMENT}\n{PROGRAM}')
ctx.rule(u'PROGRAM',u'')

ctx.rule(u'ELEMENT',u'function {IDENTIFIER} ({PARAMETER_LIST_OPT}) {COMPOUND_STATEMENT}')
ctx.rule(u'ELEMENT',u'{STATEMENT}\n')

ctx.rule(u'PARAMETER_LIST_OPT',u'')
ctx.rule(u'PARAMETER_LIST_OPT',u'{PARAMETER_LIST}')

ctx.rule(u'PARAMETER_LIST',u'{IDENTIFIER}')
ctx.rule(u'PARAMETER_LIST',u'{IDENTIFIER}, {PARAMETER_LIST}')

ctx.rule(u'COMPOUND_STATEMENT',u'\\{{STATEMENTS}\\}')

ctx.rule(u'STATEMENTS',u'')
ctx.rule(u'STATEMENTS',u'{STATEMENT}\n{STATEMENTS}')

ctx.rule(u'STATEMENT',u';')
ctx.rule(u'STATEMENT',u'if {CONDITION}{STATEMENT}')
ctx.rule(u'STATEMENT',u'if {CONDITION}{STATEMENT}\nelse {STATEMENT}')
ctx.rule(u'STATEMENT',u'while {CONDITION}{STATEMENT}')
ctx.rule(u'STATEMENT',u'{FOR_PAREN}; {EXPRESSION_OPT}; {EXPRESSION_OPT}) {STATEMENT}')
ctx.rule(u'STATEMENT',u'{FOR_BEGIN}; {EXPRESSION_OPT}; {EXPRESSION_OPT}) {STATEMENT}')
ctx.rule(u'STATEMENT',u'{FOR_BEGIN} in {EXPRESSION}) {STATEMENT}')
ctx.rule(u'STATEMENT',u'break;')
ctx.rule(u'STATEMENT',u'continue;')
ctx.rule(u'STATEMENT',u'with ({EXPRESSION}) {STATEMENT}')
ctx.rule(u'STATEMENT',u'return {EXPRESSION_OPT};')
ctx.rule(u'STATEMENT',u'{COMPOUND_STATEMENT}')
ctx.rule(u'STATEMENT',u'{VARIABLES_OR_EXPRESSION};')

ctx.rule(u'CONDITION',u'({EXPRESSION}) ')

ctx.rule(u'FOR_PAREN',u'for (')

ctx.rule(u'FOR_BEGIN',u'{FOR_PAREN}{VARIABLES_OR_EXPRESSION}')

ctx.rule(u'VARIABLES_OR_EXPRESSION',u'var {VARIABLES}')
ctx.rule(u'VARIABLES_OR_EXPRESSION',u'let {VARIABLES}')
ctx.rule(u'VARIABLES_OR_EXPRESSION',u'{EXPRESSION}')

ctx.rule(u'VARIABLES',u'{VARIABLE}')
ctx.rule(u'VARIABLES',u'{VARIABLE}, {VARIABLES}')

ctx.rule(u'VARIABLE',u'{IDENTIFIER}')
ctx.rule(u'VARIABLE',u'{IDENTIFIER} = {ASSIGNMENT_EXPRESSION}')

ctx.rule(u'EXPRESSION_OPT',u'')
ctx.rule(u'EXPRESSION_OPT',u'{EXPRESSION}')

ctx.rule(u'EXPRESSION',u'{ASSIGNMENT_EXPRESSION}')
ctx.rule(u'EXPRESSION',u'{ASSIGNMENT_EXPRESSION}, {EXPRESSION}')

ctx.rule(u'ASSIGNMENT_EXPRESSION',u'{CONDITIONAL_EXPRESSION}')
ctx.rule(u'ASSIGNMENT_EXPRESSION',u'{CONDITIONAL_EXPRESSION} {ASSIGNMENT_OPERATOR} {ASSIGNMENT_EXPRESSION}')

ctx.rule(u'CONDITIONAL_EXPRESSION',u'{OR_EXPRESSION}')
ctx.rule(u'CONDITIONAL_EXPRESSION',u'{OR_EXPRESSION}? {ASSIGNMENT_EXPRESSION} : {ASSIGNMENT_EXPRESSION}')

ctx.rule(u'OR_EXPRESSION',u'{AND_EXPRESSION}')
ctx.rule(u'OR_EXPRESSION',u'{AND_EXPRESSION} || {OR_EXPRESSION}')

ctx.rule(u'AND_EXPRESSION',u'{BITWISE_OR_EXPRESSION}')
ctx.rule(u'AND_EXPRESSION',u'{BITWISE_OR_EXPRESSION} && {AND_EXPRESSION}')

ctx.rule(u'BITWISE_OR_EXPRESSION',u'{BITWISE_XOR_EXPRESSION}')
ctx.rule(u'BITWISE_OR_EXPRESSION',u'{BITWISE_XOR_EXPRESSION} | {BITWISE_OR_EXPRESSION}')

ctx.rule(u'BITWISE_XOR_EXPRESSION',u'{BITWISE_AND_EXPRESSION}')
ctx.rule(u'BITWISE_XOR_EXPRESSION',u'{BITWISE_AND_EXPRESSION} ^ {BITWISE_XOR_EXPRESSION}')

ctx.rule(u'BITWISE_AND_EXPRESSION',u'{EQUALITY_EXPRESSION}')
ctx.rule(u'BITWISE_AND_EXPRESSION',u'{EQUALITY_EXPRESSION} & {BITWISE_AND_EXPRESSION}')

ctx.rule(u'EQUALITY_EXPRESSION',u'{RELATIONAL_EXPRESSION}')
ctx.rule(u'EQUALITY_EXPRESSION',u'{EQUALITY_EXPRESSION} == {RELATIONAL_EXPRESSION}')
ctx.rule(u'EQUALITY_EXPRESSION',u'{EQUALITY_EXPRESSION} != {RELATIONAL_EXPRESSION}')
ctx.rule(u'EQUALITY_EXPRESSION',u'{EQUALITY_EXPRESSION} === {RELATIONAL_EXPRESSION}')
ctx.rule(u'EQUALITY_EXPRESSION',u'{EQUALITY_EXPRESSION} !== {RELATIONAL_EXPRESSION}')

ctx.rule(u'RELATIONAL_EXPRESSION',u'{SHIFT_EXPRESSION}')
ctx.rule(u'RELATIONAL_EXPRESSION',u'{RELATIONAL_EXPRESSION} < {SHIFT_EXPRESSION}')
ctx.rule(u'RELATIONAL_EXPRESSION',u'{RELATIONAL_EXPRESSION} > {SHIFT_EXPRESSION}')
ctx.rule(u'RELATIONAL_EXPRESSION',u'{RELATIONAL_EXPRESSION} <= {SHIFT_EXPRESSION}')
ctx.rule(u'RELATIONAL_EXPRESSION',u'{RELATIONAL_EXPRESSION} >= {SHIFT_EXPRESSION}')
ctx.rule(u'RELATIONAL_EXPRESSION',u'{RELATIONAL_EXPRESSION} instanceof {SHIFT_EXPRESSION}')

ctx.rule(u'SHIFT_EXPRESSION',u'{ADDITIVE_EXPRESSION}')
ctx.rule(u'SHIFT_EXPRESSION',u'{SHIFT_EXPRESSION} << {ADDITIVE_EXPRESSION}')
ctx.rule(u'SHIFT_EXPRESSION',u'{SHIFT_EXPRESSION} >> {ADDITIVE_EXPRESSION}')
ctx.rule(u'SHIFT_EXPRESSION',u'{SHIFT_EXPRESSION} >>> ')

ctx.rule(u'ADDITIVE_EXPRESSION',u'{MULTIPLICATIVE_EXPRESSION}')
ctx.rule(u'ADDITIVE_EXPRESSION',u'{MULTIPLICATIVE_EXPRESSION} + {ADDITIVE_EXPRESSION}')
ctx.rule(u'ADDITIVE_EXPRESSION',u'{MULTIPLICATIVE_EXPRESSION} - {ADDITIVE_EXPRESSION}')

ctx.rule(u'MULTIPLICATIVE_EXPRESSION',u'{UNARY_EXPRESSION}')
ctx.rule(u'MULTIPLICATIVE_EXPRESSION',u'{UNARY_EXPRESSION} {MULTIPLICATIVE_OPERATOR} {MULTIPLICATIVE_EXPRESSION}')

ctx.rule(u'UNARY_EXPRESSION',u'{MEMBER_EXPRESSION}')
ctx.rule(u'UNARY_EXPRESSION',u'{UNARY_OPERATOR}{UNARY_EXPRESSION}')
ctx.rule(u'UNARY_EXPRESSION',u'{INCREMENT_OPERATOR}{MEMBER_EXPRESSION}')
ctx.rule(u'UNARY_EXPRESSION',u'{MEMBER_EXPRESSION}{INCREMENT_OPERATOR}')
ctx.rule(u'UNARY_EXPRESSION',u'new {CONSTRUCTOR}')
ctx.rule(u'UNARY_EXPRESSION',u'delete {MEMBER_EXPRESSION}')

ctx.rule(u'CONSTRUCTOR',u'this.{CONSTRUCTOR_CALL}')
ctx.rule(u'CONSTRUCTOR',u'{CONSTRUCTOR_CALL}')

ctx.rule(u'CONSTRUCTOR_CALL',u'{IDENTIFIER}')
ctx.rule(u'CONSTRUCTOR_CALL',u'{IDENTIFIER}({ARGUMENT_LIST_OPT})')
ctx.rule(u'CONSTRUCTOR_CALL',u'{IDENTIFIER}.{CONSTRUCTOR_CALL}')

ctx.rule(u'MEMBER_EXPRESSION',u'{PRIMARY_EXPRESSION}')
ctx.rule(u'MEMBER_EXPRESSION',u'{PRIMARY_EXPRESSION}.{MEMBER_EXPRESSION}')
ctx.rule(u'MEMBER_EXPRESSION',u'{PRIMARY_EXPRESSION}[{EXPRESSION}]')
ctx.rule(u'MEMBER_EXPRESSION',u'{PRIMARY_EXPRESSION}({ARGUMENT_LIST_OPT})')

ctx.rule(u'ARGUMENT_LIST_OPT',u'')
ctx.rule(u'ARGUMENT_LIST_OPT',u'{ARGUMENT_LIST}')

ctx.rule(u'ARGUMENT_LIST',u'{ASSIGNMENT_EXPRESSION}')
ctx.rule(u'ARGUMENT_LIST',u'{ASSIGNMENT_EXPRESSION}, {ARGUMENT_LIST}')

ctx.regex(u'IDENTIFIER',u'[a-zA-Z_]([0-9]|[a-zA-Z_])*')

ctx.rule(u'UNARY_OPERATOR',u'+')
ctx.rule(u'UNARY_OPERATOR',u'-')
ctx.rule(u'UNARY_OPERATOR',u'!')
ctx.rule(u'UNARY_OPERATOR',u'~')
ctx.rule(u'UNARY_OPERATOR',u'typeof ')
ctx.rule(u'UNARY_OPERATOR',u'void ')

ctx.rule(u'INCREMENT_OPERATOR',u'++')
ctx.rule(u'INCREMENT_OPERATOR',u'--')

ctx.rule(u'PRIMARY_EXPRESSION',u'({EXPRESSION})')
ctx.rule(u'PRIMARY_EXPRESSION',u'{IDENTIFIER}')
ctx.rule(u'PRIMARY_EXPRESSION',u'{LITERAL}')
ctx.rule(u'PRIMARY_EXPRESSION',u'{ARRAY_LITERAL}')
ctx.rule(u'PRIMARY_EXPRESSION',u'{OBJECT_LITERAL}')

ctx.rule(u'LITERAL',u'{VALUE_INTEGER}')
ctx.rule(u'LITERAL',u'{VALUE_DOUBLE}')
ctx.rule(u'LITERAL',u'{VALUE_STRING}')
ctx.rule(u'LITERAL',u'false')
ctx.rule(u'LITERAL',u'true')
ctx.rule(u'LITERAL',u'null')
ctx.rule(u'LITERAL',u'this')

ctx.rule(u'ARRAY_LITERAL',u'[]')
ctx.rule(u'ARRAY_LITERAL',u'[{ELISION}]')
ctx.rule(u'ARRAY_LITERAL',u'[{ELEMENT_LIST}]')
ctx.rule(u'ARRAY_LITERAL',u'[{ELEMENT_LIST}, {ELISION}]')
ctx.rule(u'ARRAY_LITERAL',u'[{ELEMENT_LIST},]')

ctx.rule(u'ELEMENT_LIST',u'{ELISION}{ASSIGNMENT_EXPRESSION}')
ctx.rule(u'ELEMENT_LIST',u'{ASSIGNMENT_EXPRESSION}')
ctx.rule(u'ELEMENT_LIST',u'{ELISION}{SPREAD_ELEMENT}')
ctx.rule(u'ELEMENT_LIST',u'{SPREAD_ELEMENT}')
ctx.rule(u'ELEMENT_LIST',u'{ELEMENT_LIST}, {ELISION}{ASSIGNMENT_EXPRESSION}')
ctx.rule(u'ELEMENT_LIST',u'{ELEMENT_LIST}, {ASSIGNMENT_EXPRESSION}')
ctx.rule(u'ELEMENT_LIST',u'{ELEMENT_LIST}, {ELISION}{SPREAD_ELEMENT}')
ctx.rule(u'ELEMENT_LIST',u'{ELEMENT_LIST}, {SPREAD_ELEMENT}')

ctx.rule(u'ELISION',u',')
ctx.rule(u'ELISION',u'{ELISION},')

ctx.rule(u'SPREAD_ELEMENT',u'...{ASSIGNMENT_EXPRESSION}')

ctx.rule(u'OBJECT_LITERAL',u'\\{\\}')
ctx.rule(u'OBJECT_LITERAL',u'\\{{PROPERTY_DEFINITION_LIST}\\}')
ctx.rule(u'OBJECT_LITERAL',u'\\{{PROPERTY_DEFINITION_LIST},\\}')

ctx.rule(u'PROPERTY_DEFINITION_LIST',u'{PROPERTY_DEFINITION}')
ctx.rule(u'PROPERTY_DEFINITION_LIST',u'{PROPERTY_DEFINITION_LIST}, {PROPERTY_DEFINITION}')

ctx.rule(u'PROPERTY_DEFINITION',u'{PROPERTY_NAME}: {ASSIGNMENT_EXPRESSION}')

ctx.rule(u'PROPERTY_NAME',u'{LITERAL_PROPERTY_NAME}')
ctx.rule(u'PROPERTY_NAME',u'{COMPUTED_PROPERTY_NAME}')

ctx.rule(u'LITERAL_PROPERTY_NAME',u'{IDENTIFIER}')
ctx.rule(u'LITERAL_PROPERTY_NAME',u'{VALUE_INTEGER}')
ctx.rule(u'LITERAL_PROPERTY_NAME',u'{VALUE_DOUBLE}')
ctx.rule(u'LITERAL_PROPERTY_NAME',u'{VALUE_STRING}')

ctx.rule(u'COMPUTED_PROPERTY_NAME',u'[{ASSIGNMENT_EXPRESSION}]')

ctx.rule(u'ASSIGNMENT_OPERATOR',u'=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'*=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'/=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'%=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'+=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'-=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'<<=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'>>=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'>>>=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'&=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'^=')
ctx.rule(u'ASSIGNMENT_OPERATOR',u'|=')

ctx.rule(u'MULTIPLICATIVE_OPERATOR',u'*')
ctx.rule(u'MULTIPLICATIVE_OPERATOR',u'/')
ctx.rule(u'MULTIPLICATIVE_OPERATOR',u'%')

### Lexer

ctx.regex(u'VALUE_INTEGER',u'[0-9]+')
ctx.rule(u'VALUE_DOUBLE',u'{VALUE_INTEGER}.{VALUE_INTEGER}')

ctx.rule(u'VALUE_STRING',u'"{STR_1}"')
ctx.rule(u'VALUE_STRING',u'\'{STR_2}\'')

ctx.rule(u'STR_1',u'')
ctx.rule(u'STR_1',u'{STR_1}{STR_1_CHAR}')

ctx.rule(u'STR_2',u'')
ctx.rule(u'STR_2',u'{STR_2}{STR_2_CHAR}')

ctx.rule(u'STR_1_CHAR',u'{CHAR}')
ctx.rule(u'STR_1_CHAR',u'{T_NS_SEPARATOR}{CHAR} ')
ctx.rule(u'STR_1_CHAR',u'\'')
ctx.rule(u'STR_1_CHAR',u'\\"')

ctx.rule(u'STR_2_CHAR',u'{CHAR}')
ctx.rule(u'STR_2_CHAR',u'{T_NS_SEPARATOR}{CHAR} ')
ctx.rule(u'STR_2_CHAR',u'"')
ctx.rule(u'STR_2_CHAR',u'\\\'')

ctx.rule(u'T_NS_SEPARATOR',u'\\')

# All chars, except three: ' " \
ctx.rule(u'CHAR', u'\x00')
ctx.rule(u'CHAR', u'\x01')
ctx.rule(u'CHAR', u'\x02')
ctx.rule(u'CHAR', u'\x03')
ctx.rule(u'CHAR', u'\x04')
ctx.rule(u'CHAR', u'\x05')
ctx.rule(u'CHAR', u'\x06')
ctx.rule(u'CHAR', u'\x07')
ctx.rule(u'CHAR', u'\x08')
ctx.rule(u'CHAR', u'\x09')
ctx.rule(u'CHAR', u'\x0A')
ctx.rule(u'CHAR', u'\x0B')
ctx.rule(u'CHAR', u'\x0C')
ctx.rule(u'CHAR', u'\x0D')
ctx.rule(u'CHAR', u'\x0E')
ctx.rule(u'CHAR', u'\x0F')
ctx.rule(u'CHAR', u'\x10')
ctx.rule(u'CHAR', u'\x11')
ctx.rule(u'CHAR', u'\x12')
ctx.rule(u'CHAR', u'\x13')
ctx.rule(u'CHAR', u'\x14')
ctx.rule(u'CHAR', u'\x15')
ctx.rule(u'CHAR', u'\x16')
ctx.rule(u'CHAR', u'\x17')
ctx.rule(u'CHAR', u'\x18')
ctx.rule(u'CHAR', u'\x19')
ctx.rule(u'CHAR', u'\x1A')
ctx.rule(u'CHAR', u'\x1B')
ctx.rule(u'CHAR', u'\x1C')
ctx.rule(u'CHAR', u'\x1D')
ctx.rule(u'CHAR', u'\x1E')
ctx.rule(u'CHAR', u'\x1F')
ctx.rule(u'CHAR', u'\x20')
ctx.rule(u'CHAR', u'\x21')
ctx.rule(u'CHAR', u'\x23')
ctx.rule(u'CHAR', u'\x24')
ctx.rule(u'CHAR', u'\x25')
ctx.rule(u'CHAR', u'\x26')
ctx.rule(u'CHAR', u'\x28')
ctx.rule(u'CHAR', u'\x29')
ctx.rule(u'CHAR', u'\x2A')
ctx.rule(u'CHAR', u'\x2B')
ctx.rule(u'CHAR', u'\x2C')
ctx.rule(u'CHAR', u'\x2D')
ctx.rule(u'CHAR', u'\x2E')
ctx.rule(u'CHAR', u'\x2F')
ctx.rule(u'CHAR', u'\x30')
ctx.rule(u'CHAR', u'\x31')
ctx.rule(u'CHAR', u'\x32')
ctx.rule(u'CHAR', u'\x33')
ctx.rule(u'CHAR', u'\x34')
ctx.rule(u'CHAR', u'\x35')
ctx.rule(u'CHAR', u'\x36')
ctx.rule(u'CHAR', u'\x37')
ctx.rule(u'CHAR', u'\x38')
ctx.rule(u'CHAR', u'\x39')
ctx.rule(u'CHAR', u'\x3A')
ctx.rule(u'CHAR', u'\x3B')
ctx.rule(u'CHAR', u'\x3C')
ctx.rule(u'CHAR', u'\x3D')
ctx.rule(u'CHAR', u'\x3E')
ctx.rule(u'CHAR', u'\x3F')
ctx.rule(u'CHAR', u'\x40')
ctx.rule(u'CHAR', u'\x41')
ctx.rule(u'CHAR', u'\x42')
ctx.rule(u'CHAR', u'\x43')
ctx.rule(u'CHAR', u'\x44')
ctx.rule(u'CHAR', u'\x45')
ctx.rule(u'CHAR', u'\x46')
ctx.rule(u'CHAR', u'\x47')
ctx.rule(u'CHAR', u'\x48')
ctx.rule(u'CHAR', u'\x49')
ctx.rule(u'CHAR', u'\x4A')
ctx.rule(u'CHAR', u'\x4B')
ctx.rule(u'CHAR', u'\x4C')
ctx.rule(u'CHAR', u'\x4D')
ctx.rule(u'CHAR', u'\x4E')
ctx.rule(u'CHAR', u'\x4F')
ctx.rule(u'CHAR', u'\x50')
ctx.rule(u'CHAR', u'\x51')
ctx.rule(u'CHAR', u'\x52')
ctx.rule(u'CHAR', u'\x53')
ctx.rule(u'CHAR', u'\x54')
ctx.rule(u'CHAR', u'\x55')
ctx.rule(u'CHAR', u'\x56')
ctx.rule(u'CHAR', u'\x57')
ctx.rule(u'CHAR', u'\x58')
ctx.rule(u'CHAR', u'\x59')
ctx.rule(u'CHAR', u'\x5A')
ctx.rule(u'CHAR', u'\x5B')
ctx.rule(u'CHAR', u'\x5D')
ctx.rule(u'CHAR', u'\x5E')
ctx.rule(u'CHAR', u'\x5F')
ctx.rule(u'CHAR', u'\x60')
ctx.rule(u'CHAR', u'\x61')
ctx.rule(u'CHAR', u'\x62')
ctx.rule(u'CHAR', u'\x63')
ctx.rule(u'CHAR', u'\x64')
ctx.rule(u'CHAR', u'\x65')
ctx.rule(u'CHAR', u'\x66')
ctx.rule(u'CHAR', u'\x67')
ctx.rule(u'CHAR', u'\x68')
ctx.rule(u'CHAR', u'\x69')
ctx.rule(u'CHAR', u'\x6A')
ctx.rule(u'CHAR', u'\x6B')
ctx.rule(u'CHAR', u'\x6C')
ctx.rule(u'CHAR', u'\x6D')
ctx.rule(u'CHAR', u'\x6E')
ctx.rule(u'CHAR', u'\x6F')
ctx.rule(u'CHAR', u'\x70')
ctx.rule(u'CHAR', u'\x71')
ctx.rule(u'CHAR', u'\x72')
ctx.rule(u'CHAR', u'\x73')
ctx.rule(u'CHAR', u'\x74')
ctx.rule(u'CHAR', u'\x75')
ctx.rule(u'CHAR', u'\x76')
ctx.rule(u'CHAR', u'\x77')
ctx.rule(u'CHAR', u'\x78')
ctx.rule(u'CHAR', u'\x79')
ctx.rule(u'CHAR', u'\x7A')
ctx.rule(u'CHAR', u'\x7B')
ctx.rule(u'CHAR', u'\x7C')
ctx.rule(u'CHAR', u'\x7D')
ctx.rule(u'CHAR', u'\x7E')
ctx.rule(u'CHAR', u'\x7F')
