ctx.rule(u'START',u'<?php\n{TOP_STATEMENT_LIST}\n?>')

ctx.rule(u'RESERVED_NON_MODIFIERS',u'include')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'include_once')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'eval')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'require')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'require_once')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'or')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'xor')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'and')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'instanceof')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'new')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'clone')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'exit')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'if')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'elseif')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'else')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'endif')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'echo')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'do')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'while')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'endwhile')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'for')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'endfor')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'foreach')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'endforeach')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'declare')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'enddeclare')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'as')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'try')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'catch')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'finally')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'throw')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'use')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'insteadof')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'global')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'var')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'unset')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'isset')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'empty')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'continue')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'goto')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'function')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'const')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'return')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'print')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'yield')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'list')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'switch')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'endswitch')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'case')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'default')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'break')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'array')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'callable')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'extends')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'implements')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'namespace')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'trait')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'interface')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'{T_CLASS}')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'__CLASS__')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'__TRAIT__')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'__FUNCTION__')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'__METHOD__')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'__LINE__')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'__FILE__')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'__DIR__')
ctx.rule(u'RESERVED_NON_MODIFIERS',u'__NAMESPACE__')

ctx.rule(u'SEMI_RESERVED',u'{RESERVED_NON_MODIFIERS}')
ctx.rule(u'SEMI_RESERVED',u'static')
ctx.rule(u'SEMI_RESERVED',u'abstract')
ctx.rule(u'SEMI_RESERVED',u'final')
ctx.rule(u'SEMI_RESERVED',u'private')
ctx.rule(u'SEMI_RESERVED',u'protected')
ctx.rule(u'SEMI_RESERVED',u'public')

ctx.rule(u'IDENTIFIER',u'{T_STRING}')
ctx.rule(u'IDENTIFIER',u'{SEMI_RESERVED}')

ctx.rule(u'TOP_STATEMENT_LIST',u'{TOP_STATEMENT_LIST}\n{TOP_STATEMENT}')
ctx.rule(u'TOP_STATEMENT_LIST',u'')

ctx.rule(u'NAMESPACE_NAME',u'{T_STRING}')
ctx.rule(u'NAMESPACE_NAME',u'{NAMESPACE_NAME}{T_NS_SEPARATOR}{T_STRING}')

ctx.rule(u'NAME',u'{NAMESPACE_NAME}')
ctx.rule(u'NAME',u'namespace {T_NS_SEPARATOR}{NAMESPACE_NAME}')
ctx.rule(u'NAME',u'{T_NS_SEPARATOR}{NAMESPACE_NAME}')

ctx.rule(u'TOP_STATEMENT',u'{STATEMENT}')
ctx.rule(u'TOP_STATEMENT',u'{FUNCTION_DECLARATION_STATEMENT}')
ctx.rule(u'TOP_STATEMENT',u'{CLASS_DECLARATION_STATEMENT}')
ctx.rule(u'TOP_STATEMENT',u'{TRAIT_DECLARATION_STATEMENT}')
ctx.rule(u'TOP_STATEMENT',u'{INTERFACE_DECLARATION_STATEMENT}')
ctx.rule(u'TOP_STATEMENT',u'__halt_compiler();')
ctx.rule(u'TOP_STATEMENT',u'namespace {NAMESPACE_NAME};')
ctx.rule(u'TOP_STATEMENT',u'namespace {NAMESPACE_NAME}\\{{TOP_STATEMENT_LIST}\\}')
ctx.rule(u'TOP_STATEMENT',u'namespace \\{{TOP_STATEMENT_LIST}\\}')
ctx.rule(u'TOP_STATEMENT',u'use {MIXED_GROUP_USE_DECLARATION};')
ctx.rule(u'TOP_STATEMENT',u'use {USE_TYPE} {GROUP_USE_DECLARATION};')
ctx.rule(u'TOP_STATEMENT',u'use {USE_DECLARATIONS};')
ctx.rule(u'TOP_STATEMENT',u'use {USE_TYPE} {USE_DECLARATIONS};')
ctx.rule(u'TOP_STATEMENT',u'const {CONST_LIST};')

ctx.rule(u'USE_TYPE',u'function')
ctx.rule(u'USE_TYPE',u'const')

ctx.rule(u'GROUP_USE_DECLARATION',u'{NAMESPACE_NAME}{T_NS_SEPARATOR}\\{{UNPREFIXED_USE_DECLARATIONS}{POSSIBLE_COMMA}\\}')
ctx.rule(u'GROUP_USE_DECLARATION',u'{T_NS_SEPARATOR}{NAMESPACE_NAME}{T_NS_SEPARATOR}\\{{UNPREFIXED_USE_DECLARATIONS}{POSSIBLE_COMMA}\\}')

ctx.rule(u'MIXED_GROUP_USE_DECLARATION',u'{NAMESPACE_NAME}{T_NS_SEPARATOR}\\{{INLINE_USE_DECLARATIONS}{POSSIBLE_COMMA}\\}')
ctx.rule(u'MIXED_GROUP_USE_DECLARATION',u'{T_NS_SEPARATOR}{NAMESPACE_NAME}{T_NS_SEPARATOR}\\{{INLINE_USE_DECLARATIONS}{POSSIBLE_COMMA}\\}')

ctx.rule(u'POSSIBLE_COMMA',u',')
ctx.rule(u'POSSIBLE_COMMA',u'')

ctx.rule(u'INLINE_USE_DECLARATIONS',u'{INLINE_USE_DECLARATIONS}, {INLINE_USE_DECLARATION}')
ctx.rule(u'INLINE_USE_DECLARATIONS',u'{INLINE_USE_DECLARATION}')

ctx.rule(u'UNPREFIXED_USE_DECLARATIONS',u'{UNPREFIXED_USE_DECLARATIONS}, {UNPREFIXED_USE_DECLARATION}')
ctx.rule(u'UNPREFIXED_USE_DECLARATIONS',u'{UNPREFIXED_USE_DECLARATION}')

ctx.rule(u'USE_DECLARATIONS',u'{USE_DECLARATIONS}, {USE_DECLARATION}')
ctx.rule(u'USE_DECLARATIONS',u'{USE_DECLARATION}')

ctx.rule(u'INLINE_USE_DECLARATION',u'{UNPREFIXED_USE_DECLARATION}')
ctx.rule(u'INLINE_USE_DECLARATION',u'{USE_TYPE} {UNPREFIXED_USE_DECLARATION}')

ctx.rule(u'UNPREFIXED_USE_DECLARATION',u'{NAMESPACE_NAME}')
ctx.rule(u'UNPREFIXED_USE_DECLARATION',u'{NAMESPACE_NAME} as {T_STRING}')

ctx.rule(u'USE_DECLARATION',u'{UNPREFIXED_USE_DECLARATION}')
ctx.rule(u'USE_DECLARATION',u'{T_NS_SEPARATOR}{UNPREFIXED_USE_DECLARATION}')

ctx.rule(u'CONST_LIST',u'{CONST_LIST}, {CONST_DECL}')
ctx.rule(u'CONST_LIST',u'{CONST_DECL}')

ctx.rule(u'INNER_STATEMENT_LIST',u'{INNER_STATEMENT_LIST}{INNER_STATEMENT}\n')
ctx.rule(u'INNER_STATEMENT_LIST',u'\n')

ctx.rule(u'INNER_STATEMENT',u'{STATEMENT}')
ctx.rule(u'INNER_STATEMENT',u'{FUNCTION_DECLARATION_STATEMENT}')
ctx.rule(u'INNER_STATEMENT',u'{CLASS_DECLARATION_STATEMENT}')
ctx.rule(u'INNER_STATEMENT',u'{TRAIT_DECLARATION_STATEMENT}')
ctx.rule(u'INNER_STATEMENT',u'{INTERFACE_DECLARATION_STATEMENT}')
ctx.rule(u'INNER_STATEMENT',u'__halt_compiler();')

ctx.rule(u'STATEMENT',u'\\{{INNER_STATEMENT_LIST}\\}')
ctx.rule(u'STATEMENT',u'{IF_STMT}')
ctx.rule(u'STATEMENT',u'{ALT_IF_STMT}')
ctx.rule(u'STATEMENT',u'while ({EXPR})\n{WHILE_STATEMENT}')
ctx.rule(u'STATEMENT',u'do\n{STATEMENT}\nwhile ({EXPR});')
ctx.rule(u'STATEMENT',u'for ({FOR_EXPRS}; {FOR_EXPRS}; {FOR_EXPRS})\n{FOR_STATEMENT}')
ctx.rule(u'STATEMENT',u'switch ({EXPR})\n{SWITCH_CASE_LIST}')
ctx.rule(u'STATEMENT',u'break {OPTIONAL_EXPR};')
ctx.rule(u'STATEMENT',u'continue {OPTIONAL_EXPR};')
ctx.rule(u'STATEMENT',u'return {OPTIONAL_EXPR};')
ctx.rule(u'STATEMENT',u'global {GLOBAL_VAR_LIST};')
ctx.rule(u'STATEMENT',u'static {STATIC_VAR_LIST};')
ctx.rule(u'STATEMENT',u'echo {ECHO_EXPR_LIST};')
ctx.rule(u'STATEMENT',u'{EXPR};')
ctx.rule(u'STATEMENT',u'unset ({UNSET_VARIABLES}{POSSIBLE_COMMA});')
ctx.rule(u'STATEMENT',u'foreach ({EXPR} as {FOREACH_VARIABLE}) {FOREACH_STATEMENT}')
ctx.rule(u'STATEMENT',u'foreach ({EXPR} as {FOREACH_VARIABLE} => {FOREACH_VARIABLE}) {FOREACH_STATEMENT}')
ctx.rule(u'STATEMENT',u'declare ({CONST_LIST})')
ctx.rule(u'STATEMENT',u'{DECLARE_STATEMENT}')
ctx.rule(u'STATEMENT',u';')
ctx.rule(u'STATEMENT',u'try \\{{INNER_STATEMENT_LIST}\\}\n{CATCH_LIST}\n{FINALLY_STATEMENT}')
ctx.rule(u'STATEMENT',u'throw {EXPR};')
ctx.rule(u'STATEMENT',u'goto {T_STRING};')
ctx.rule(u'STATEMENT',u'{T_STRING}:')

ctx.rule(u'CATCH_LIST',u'')
ctx.rule(u'CATCH_LIST',u'{CATCH_LIST}\ncatch ({CATCH_NAME_LIST}{T_VARIABLE}) \\{{INNER_STATEMENT_LIST}\\}')

ctx.rule(u'CATCH_NAME_LIST',u'{NAME}')
ctx.rule(u'CATCH_NAME_LIST',u'{CATCH_NAME_LIST} | {NAME}')

ctx.rule(u'FINALLY_STATEMENT',u'')
ctx.rule(u'FINALLY_STATEMENT',u'finally \\{{INNER_STATEMENT_LIST}\\}')

ctx.rule(u'UNSET_VARIABLES',u'{UNSET_VARIABLE}')
ctx.rule(u'UNSET_VARIABLES',u'{UNSET_VARIABLES}, {UNSET_VARIABLE}')

ctx.rule(u'UNSET_VARIABLE',u'{VARIABLE}')

ctx.rule(u'FUNCTION_DECLARATION_STATEMENT',u'function {RETURNS_REF}{T_STRING} ({PARAMETER_LIST}){RETURN_TYPE}\\{{INNER_STATEMENT_LIST}\\}')

ctx.rule(u'IS_REFERENCE',u'')
ctx.rule(u'IS_REFERENCE',u'&')

ctx.rule(u'IS_VARIADIC',u'')
ctx.rule(u'IS_VARIADIC',u'...')

ctx.rule(u'CLASS_DECLARATION_STATEMENT',u'{CLASS_MODIFIERS} {T_CLASS} {T_STRING} {EXTENDS_FROM} {IMPLEMENTS_LIST} \\{{CLASS_STATEMENT_LIST}\\}')
ctx.rule(u'CLASS_DECLARATION_STATEMENT',u'{T_CLASS} {T_STRING} {EXTENDS_FROM} {IMPLEMENTS_LIST} \\{{CLASS_STATEMENT_LIST}\\}')

ctx.rule(u'CLASS_MODIFIERS',u'{CLASS_MODIFIER}')
ctx.rule(u'CLASS_MODIFIERS',u'{CLASS_MODIFIERS} {CLASS_MODIFIER}')

ctx.rule(u'CLASS_MODIFIER',u'abstract')
ctx.rule(u'CLASS_MODIFIER',u'final')

ctx.rule(u'TRAIT_DECLARATION_STATEMENT',u'trait {T_STRING}\\{{CLASS_STATEMENT_LIST}\\}')

ctx.rule(u'INTERFACE_DECLARATION_STATEMENT',u'interface {T_STRING}{INTERFACE_EXTENDS_LIST} \\{{CLASS_STATEMENT_LIST}\\}')

ctx.rule(u'EXTENDS_FROM',u'')
ctx.rule(u'EXTENDS_FROM',u'extends {NAME}')

ctx.rule(u'INTERFACE_EXTENDS_LIST',u'')
ctx.rule(u'INTERFACE_EXTENDS_LIST',u' extends {NAME_LIST}')

ctx.rule(u'IMPLEMENTS_LIST',u'')
ctx.rule(u'IMPLEMENTS_LIST',u'implements {NAME_LIST}')

ctx.rule(u'FOREACH_VARIABLE',u'{VARIABLE}')
ctx.rule(u'FOREACH_VARIABLE',u'&{VARIABLE}')
ctx.rule(u'FOREACH_VARIABLE',u'list({ARRAY_PAIR_LIST})')
ctx.rule(u'FOREACH_VARIABLE',u'[{ARRAY_PAIR_LIST}]')

ctx.rule(u'FOR_STATEMENT',u'{STATEMENT}')
ctx.rule(u'FOR_STATEMENT',u':{INNER_STATEMENT_LIST}\nendfor;')

ctx.rule(u'FOREACH_STATEMENT',u'{STATEMENT}')
ctx.rule(u'FOREACH_STATEMENT',u':{INNER_STATEMENT_LIST}\nendforeach;')

ctx.rule(u'DECLARE_STATEMENT',u'{STATEMENT}')
ctx.rule(u'DECLARE_STATEMENT',u':{INNER_STATEMENT_LIST}\nenddeclare;')

ctx.rule(u'SWITCH_CASE_LIST',u'\\{{CASE_LIST}\\}')
ctx.rule(u'SWITCH_CASE_LIST',u'\\{;{CASE_LIST}\\}')
ctx.rule(u'SWITCH_CASE_LIST',u':{CASE_LIST}\nendswitch;')
ctx.rule(u'SWITCH_CASE_LIST',u':;{CASE_LIST}\nendswitch;')

ctx.rule(u'CASE_LIST',u'')
ctx.rule(u'CASE_LIST',u'{CASE_LIST} case {EXPR}{CASE_SEPARATOR}\n{INNER_STATEMENT_LIST}')
ctx.rule(u'CASE_LIST',u'{CASE_LIST} default {CASE_SEPARATOR}\n{INNER_STATEMENT_LIST}')

ctx.rule(u'CASE_SEPARATOR',u':')
ctx.rule(u'CASE_SEPARATOR',u';')

ctx.rule(u'WHILE_STATEMENT',u'{STATEMENT}')
ctx.rule(u'WHILE_STATEMENT',u':{INNER_STATEMENT_LIST}\nendwhile;')

ctx.rule(u'IF_STMT_WITHOUT_ELSE',u'if ({EXPR})\n{STATEMENT}')
ctx.rule(u'IF_STMT_WITHOUT_ELSE',u'{IF_STMT_WITHOUT_ELSE}\nelseif ({EXPR})\n{STATEMENT}')

ctx.rule(u'IF_STMT',u'{IF_STMT_WITHOUT_ELSE}')
ctx.rule(u'IF_STMT',u'{IF_STMT_WITHOUT_ELSE}\nelse\n{STATEMENT}')

ctx.rule(u'ALT_IF_STMT_WITHOUT_ELSE',u'if ({EXPR}):\n{INNER_STATEMENT_LIST}')
ctx.rule(u'ALT_IF_STMT_WITHOUT_ELSE',u'{ALT_IF_STMT_WITHOUT_ELSE}\nelseif ({EXPR}):\n{INNER_STATEMENT_LIST}')

ctx.rule(u'ALT_IF_STMT',u'{ALT_IF_STMT_WITHOUT_ELSE}\nendif;')
ctx.rule(u'ALT_IF_STMT',u'{ALT_IF_STMT_WITHOUT_ELSE}\nelse:\n{INNER_STATEMENT_LIST}\nendif;')

ctx.rule(u'PARAMETER_LIST',u'{NON_EMPTY_PARAMETER_LIST}')
ctx.rule(u'PARAMETER_LIST',u'')

ctx.rule(u'NON_EMPTY_PARAMETER_LIST',u'{PARAMETER}')
ctx.rule(u'NON_EMPTY_PARAMETER_LIST',u'{NON_EMPTY_PARAMETER_LIST}, {PARAMETER}')

ctx.rule(u'PARAMETER',u'{OPTIONAL_TYPE} {IS_REFERENCE} {IS_VARIADIC} {T_VARIABLE}')
ctx.rule(u'PARAMETER',u'{OPTIONAL_TYPE} {IS_REFERENCE} {IS_VARIADIC} {T_VARIABLE} = {EXPR}')

ctx.rule(u'OPTIONAL_TYPE',u'')
ctx.rule(u'OPTIONAL_TYPE',u'{TYPE_EXPR}')

ctx.rule(u'TYPE_EXPR',u'{TYPE}')
ctx.rule(u'TYPE_EXPR',u'?{TYPE}')

ctx.rule(u'TYPE',u'array')
ctx.rule(u'TYPE',u'callable')
ctx.rule(u'TYPE',u'{NAME}')

ctx.rule(u'RETURN_TYPE',u'')
ctx.rule(u'RETURN_TYPE',u':{TYPE_EXPR}')

ctx.rule(u'ARGUMENT_LIST',u'()')
ctx.rule(u'ARGUMENT_LIST',u'({NON_EMPTY_ARGUMENT_LIST}{POSSIBLE_COMMA})')

ctx.rule(u'NON_EMPTY_ARGUMENT_LIST',u'{ARGUMENT}')
ctx.rule(u'NON_EMPTY_ARGUMENT_LIST',u'{NON_EMPTY_ARGUMENT_LIST}, {ARGUMENT}')

ctx.rule(u'ARGUMENT',u'{EXPR}')
ctx.rule(u'ARGUMENT',u'...{EXPR}')

ctx.rule(u'GLOBAL_VAR_LIST',u'{GLOBAL_VAR_LIST}, {GLOBAL_VAR}')
ctx.rule(u'GLOBAL_VAR_LIST',u'{GLOBAL_VAR}')

ctx.rule(u'GLOBAL_VAR',u'{SIMPLE_VARIABLE}')

ctx.rule(u'STATIC_VAR_LIST',u'{STATIC_VAR_LIST}, {STATIC_VAR}')
ctx.rule(u'STATIC_VAR_LIST',u'{STATIC_VAR}')

ctx.rule(u'STATIC_VAR',u'{T_VARIABLE}')
ctx.rule(u'STATIC_VAR',u'{T_VARIABLE} = {EXPR}')

ctx.rule(u'CLASS_STATEMENT_LIST',u'{CLASS_STATEMENT_LIST} {CLASS_STATEMENT}')
ctx.rule(u'CLASS_STATEMENT_LIST',u'')

ctx.rule(u'CLASS_STATEMENT',u'{VARIABLE_MODIFIERS} {PROPERTY_LIST};')
ctx.rule(u'CLASS_STATEMENT',u'{METHOD_MODIFIERS} const {CLASS_CONST_LIST};')
ctx.rule(u'CLASS_STATEMENT',u'use {NAME_LIST} {TRAIT_ADAPTATIONS}')
ctx.rule(u'CLASS_STATEMENT',u'{METHOD_MODIFIERS} function {RETURNS_REF} {IDENTIFIER} ({PARAMETER_LIST}) {RETURN_TYPE} {METHOD_BODY}')

ctx.rule(u'NAME_LIST',u'{NAME}')
ctx.rule(u'NAME_LIST',u'{NAME_LIST}, {NAME}')

ctx.rule(u'TRAIT_ADAPTATIONS',u';')
ctx.rule(u'TRAIT_ADAPTATIONS',u'\\{\\}')
ctx.rule(u'TRAIT_ADAPTATIONS',u'\\{{TRAIT_ADAPTATION_LIST}\\}')

ctx.rule(u'TRAIT_ADAPTATION_LIST',u'{TRAIT_ADAPTATION}')
ctx.rule(u'TRAIT_ADAPTATION_LIST',u'{TRAIT_ADAPTATION_LIST} {TRAIT_ADAPTATION}')

ctx.rule(u'TRAIT_ADAPTATION',u'{TRAIT_PRECEDENCE};')
ctx.rule(u'TRAIT_ADAPTATION',u'{TRAIT_ALIAS};')

ctx.rule(u'TRAIT_PRECEDENCE',u'{ABSOLUTE_TRAIT_METHOD_REFERENCE} insteadof {NAME_LIST}')

ctx.rule(u'TRAIT_ALIAS',u'{TRAIT_METHOD_REFERENCE} as {T_STRING}')
ctx.rule(u'TRAIT_ALIAS',u'{TRAIT_METHOD_REFERENCE} as {RESERVED_NON_MODIFIERS}')
ctx.rule(u'TRAIT_ALIAS',u'{TRAIT_METHOD_REFERENCE} as {MEMBER_MODIFIER} {IDENTIFIER}')
ctx.rule(u'TRAIT_ALIAS',u'{TRAIT_METHOD_REFERENCE} as {MEMBER_MODIFIER}')

ctx.rule(u'TRAIT_METHOD_REFERENCE',u'{IDENTIFIER}')
ctx.rule(u'TRAIT_METHOD_REFERENCE',u'{ABSOLUTE_TRAIT_METHOD_REFERENCE}')

ctx.rule(u'ABSOLUTE_TRAIT_METHOD_REFERENCE',u'{NAME}::{IDENTIFIER}')

ctx.rule(u'METHOD_BODY',u';')
ctx.rule(u'METHOD_BODY',u'\\{{INNER_STATEMENT_LIST}\\}')

ctx.rule(u'VARIABLE_MODIFIERS',u'{NON_EMPTY_MEMBER_MODIFIERS}')
ctx.rule(u'VARIABLE_MODIFIERS',u'var')

ctx.rule(u'METHOD_MODIFIERS',u'')
ctx.rule(u'METHOD_MODIFIERS',u'{NON_EMPTY_MEMBER_MODIFIERS}')

ctx.rule(u'NON_EMPTY_MEMBER_MODIFIERS',u'{MEMBER_MODIFIER}')
ctx.rule(u'NON_EMPTY_MEMBER_MODIFIERS',u'{NON_EMPTY_MEMBER_MODIFIERS} {MEMBER_MODIFIER}')

ctx.rule(u'MEMBER_MODIFIER',u'public')
ctx.rule(u'MEMBER_MODIFIER',u'protected')
ctx.rule(u'MEMBER_MODIFIER',u'private')
ctx.rule(u'MEMBER_MODIFIER',u'static')
ctx.rule(u'MEMBER_MODIFIER',u'abstract')
ctx.rule(u'MEMBER_MODIFIER',u'final')

ctx.rule(u'PROPERTY_LIST',u'{PROPERTY_LIST}, {PROPERTY}')
ctx.rule(u'PROPERTY_LIST',u'{PROPERTY}')

ctx.rule(u'PROPERTY',u'{T_VARIABLE}')
ctx.rule(u'PROPERTY',u'{T_VARIABLE}={EXPR}')

ctx.rule(u'CLASS_CONST_LIST',u'{CLASS_CONST_LIST}, {CLASS_CONST_DECL}')
ctx.rule(u'CLASS_CONST_LIST',u'{CLASS_CONST_DECL}')

ctx.rule(u'CLASS_CONST_DECL',u'{IDENTIFIER}={EXPR}')

ctx.rule(u'CONST_DECL',u'{T_STRING}={EXPR}')

ctx.rule(u'ECHO_EXPR_LIST',u'{ECHO_EXPR_LIST}, {ECHO_EXPR}')
ctx.rule(u'ECHO_EXPR_LIST',u'{ECHO_EXPR}')

ctx.rule(u'ECHO_EXPR',u'{EXPR}')

ctx.rule(u'FOR_EXPRS',u'')
ctx.rule(u'FOR_EXPRS',u'{NON_EMPTY_FOR_EXPRS}')

ctx.rule(u'NON_EMPTY_FOR_EXPRS',u'{NON_EMPTY_FOR_EXPRS}, {EXPR}')
ctx.rule(u'NON_EMPTY_FOR_EXPRS',u'{EXPR}')

ctx.rule(u'ANONYMOUS_CLASS',u'{T_CLASS} {CTOR_ARGUMENTS} {EXTENDS_FROM} {IMPLEMENTS_LIST} \\{{CLASS_STATEMENT_LIST}\\}')

ctx.rule(u'NEW_EXPR',u'new {CLASS_NAME_REFERENCE} {CTOR_ARGUMENTS}')
ctx.rule(u'NEW_EXPR',u'new {ANONYMOUS_CLASS}')

ctx.rule(u'EXPR',u'{VARIABLE}')
ctx.rule(u'EXPR',u'list ({ARRAY_PAIR_LIST}) = {EXPR}')
ctx.rule(u'EXPR',u'[{ARRAY_PAIR_LIST}] = {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} = {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} =& {VARIABLE}')
ctx.rule(u'EXPR',u'clone {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} += {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} -= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} *= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} **= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} /= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} .= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} %= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} &= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} |= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} ^= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} <<= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE} >>= {EXPR}')
ctx.rule(u'EXPR',u'{VARIABLE}++')
ctx.rule(u'EXPR',u'++{VARIABLE}')
ctx.rule(u'EXPR',u'{VARIABLE}--')
ctx.rule(u'EXPR',u'--{VARIABLE}')
ctx.rule(u'EXPR',u'{EXPR} || {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} && {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} or {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} and {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} xor {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} | {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} & {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} ^ {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} . {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} + {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} - {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} * {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} ** {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} / {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} % {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} << {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} >> {EXPR}')
ctx.rule(u'EXPR',u'+{EXPR}')
ctx.rule(u'EXPR',u'-{EXPR}')
ctx.rule(u'EXPR',u'!{EXPR}')
ctx.rule(u'EXPR',u'~{EXPR}')
ctx.rule(u'EXPR',u'{EXPR} === {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} !== {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} == {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} != {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} < {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} <= {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} > {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} >= {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} <=> {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} instanceof {CLASS_NAME_REFERENCE}')
ctx.rule(u'EXPR',u'({EXPR})')
ctx.rule(u'EXPR',u'{NEW_EXPR}')
ctx.rule(u'EXPR',u'{EXPR} ? {EXPR} : {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} ? : {EXPR}')
ctx.rule(u'EXPR',u'{EXPR} ?? {EXPR}')
ctx.rule(u'EXPR',u'{INTERNAL_FUNCTIONS_IN_YACC}')
ctx.rule(u'EXPR',u'(int) {EXPR}')
ctx.rule(u'EXPR',u'(double) {EXPR}')
ctx.rule(u'EXPR',u'(string) {EXPR}')
ctx.rule(u'EXPR',u'(array) {EXPR}')
ctx.rule(u'EXPR',u'(object) {EXPR}')
ctx.rule(u'EXPR',u'(bool) {EXPR}')
ctx.rule(u'EXPR',u'(unset) {EXPR}')
ctx.rule(u'EXPR',u'(exit) {EXIT_EXPR}')
ctx.rule(u'EXPR',u'@{EXPR}')
ctx.rule(u'EXPR',u'{SCALAR}')
ctx.rule(u'EXPR',u'`{BACKTICKS_EXPR}`')
ctx.rule(u'EXPR',u'print {EXPR}')
ctx.rule(u'EXPR',u'yield')
ctx.rule(u'EXPR',u'yield {EXPR}')
ctx.rule(u'EXPR',u'yield {EXPR} => {EXPR}')
ctx.rule(u'EXPR',u'yield from {EXPR}')
ctx.rule(u'EXPR',u'function {RETURNS_REF} ({PARAMETER_LIST}) {LEXICAL_VARS} {RETURN_TYPE} \\{{INNER_STATEMENT_LIST}\\}')
ctx.rule(u'EXPR',u'static function {RETURNS_REF} ({PARAMETER_LIST}) {LEXICAL_VARS} {RETURN_TYPE} \\{{INNER_STATEMENT_LIST}\\}')

ctx.rule(u'RETURNS_REF',u'')
ctx.rule(u'RETURNS_REF',u'&')

ctx.rule(u'LEXICAL_VARS',u'')
ctx.rule(u'LEXICAL_VARS',u'use ({LEXICAL_VAR_LIST})')

ctx.rule(u'LEXICAL_VAR_LIST',u'{LEXICAL_VAR_LIST}, {LEXICAL_VAR}')
ctx.rule(u'LEXICAL_VAR_LIST',u'{LEXICAL_VAR}')

ctx.rule(u'LEXICAL_VAR',u'{T_VARIABLE}')
ctx.rule(u'LEXICAL_VAR',u'&{T_VARIABLE}')

ctx.rule(u'FUNCTION_CALL',u'{NAME} {ARGUMENT_LIST}')
ctx.rule(u'FUNCTION_CALL',u'{CLASS_NAME}::{MEMBER_NAME} {ARGUMENT_LIST}')
ctx.rule(u'FUNCTION_CALL',u'{VARIABLE_CLASS_NAME}::{MEMBER_NAME} {ARGUMENT_LIST}')
ctx.rule(u'FUNCTION_CALL',u'{CALLABLE_EXPR} {ARGUMENT_LIST}')

ctx.rule(u'CLASS_NAME',u'static')
ctx.rule(u'CLASS_NAME',u'{NAME}')

ctx.rule(u'CLASS_NAME_REFERENCE',u'{CLASS_NAME}')
ctx.rule(u'CLASS_NAME_REFERENCE',u'{NEW_VARIABLE}')

ctx.rule(u'EXIT_EXPR',u'')
ctx.rule(u'EXIT_EXPR',u'({OPTIONAL_EXPR})')

ctx.rule(u'BACKTICKS_EXPR',u'')
ctx.rule(u'BACKTICKS_EXPR',u'{ENCAPS_LIST}')

ctx.rule(u'CTOR_ARGUMENTS',u'')
ctx.rule(u'CTOR_ARGUMENTS',u'{ARGUMENT_LIST}')

ctx.rule(u'DEREFERENCABLE_SCALAR',u'array({ARRAY_PAIR_LIST})')
ctx.rule(u'DEREFERENCABLE_SCALAR',u'[{ARRAY_PAIR_LIST}]')
ctx.rule(u'DEREFERENCABLE_SCALAR',u'{T_CONSTANT_ENCAPSED_STRING}')

ctx.rule(u'SCALAR',u'{LNUMBER}')
ctx.rule(u'SCALAR',u'{DNUMBER}')
ctx.rule(u'SCALAR',u'__LINE__')
ctx.rule(u'SCALAR',u'__FILE__')
ctx.rule(u'SCALAR',u'__DIR__')
ctx.rule(u'SCALAR',u'__TRAIT__')
ctx.rule(u'SCALAR',u'__METHOD__')
ctx.rule(u'SCALAR',u'__FUNCTION__')
ctx.rule(u'SCALAR',u'__NAMESPACE__')
ctx.rule(u'SCALAR',u'__CLASS__')
ctx.rule(u'SCALAR',u'"{ENCAPS_LIST}"')
ctx.rule(u'SCALAR',u'{DEREFERENCABLE_SCALAR}')
ctx.rule(u'SCALAR',u'{CONSTANT}')

ctx.rule(u'CONSTANT',u'{NAME}')
ctx.rule(u'CONSTANT',u'{CLASS_NAME}::{IDENTIFIER}')
ctx.rule(u'CONSTANT',u'{VARIABLE_CLASS_NAME}::{IDENTIFIER}')

ctx.rule(u'OPTIONAL_EXPR',u'')
ctx.rule(u'OPTIONAL_EXPR',u'{EXPR}')

ctx.rule(u'VARIABLE_CLASS_NAME',u'{DEREFERENCABLE}')

ctx.rule(u'DEREFERENCABLE',u'{VARIABLE}')
ctx.rule(u'DEREFERENCABLE',u'({EXPR})')
ctx.rule(u'DEREFERENCABLE',u'{DEREFERENCABLE_SCALAR}')

ctx.rule(u'CALLABLE_EXPR',u'{CALLABLE_VARIABLE}')
ctx.rule(u'CALLABLE_EXPR',u'({EXPR})')
ctx.rule(u'CALLABLE_EXPR',u'{DEREFERENCABLE_SCALAR}')

ctx.rule(u'CALLABLE_VARIABLE',u'{SIMPLE_VARIABLE}')
ctx.rule(u'CALLABLE_VARIABLE',u'{DEREFERENCABLE}[{OPTIONAL_EXPR}]')
ctx.rule(u'CALLABLE_VARIABLE',u'{CONSTANT}[{OPTIONAL_EXPR}]')
ctx.rule(u'CALLABLE_VARIABLE',u'{DEREFERENCABLE}\\{{EXPR}\\}')
ctx.rule(u'CALLABLE_VARIABLE',u'{DEREFERENCABLE}->{PROPERTY_NAME} {ARGUMENT_LIST}')
ctx.rule(u'CALLABLE_VARIABLE',u'{FUNCTION_CALL}')

ctx.rule(u'VARIABLE',u'{CALLABLE_VARIABLE}')
ctx.rule(u'VARIABLE',u'{STATIC_MEMBER}')
ctx.rule(u'VARIABLE',u'{DEREFERENCABLE}->{PROPERTY_NAME}')

ctx.rule(u'SIMPLE_VARIABLE',u'{T_VARIABLE}')
ctx.rule(u'SIMPLE_VARIABLE',u'$\\{{EXPR}\\}')
ctx.rule(u'SIMPLE_VARIABLE',u'${SIMPLE_VARIABLE}')

ctx.rule(u'STATIC_MEMBER',u'{CLASS_NAME}::{SIMPLE_VARIABLE}')
ctx.rule(u'STATIC_MEMBER',u'{VARIABLE_CLASS_NAME}::{SIMPLE_VARIABLE}')

ctx.rule(u'NEW_VARIABLE',u'{SIMPLE_VARIABLE}')
ctx.rule(u'NEW_VARIABLE',u'{NEW_VARIABLE}[{OPTIONAL_EXPR}]')
ctx.rule(u'NEW_VARIABLE',u'{NEW_VARIABLE}\\{{EXPR}\\}')
ctx.rule(u'NEW_VARIABLE',u'{NEW_VARIABLE}->{PROPERTY_NAME}')
ctx.rule(u'NEW_VARIABLE',u'{CLASS_NAME}::{SIMPLE_VARIABLE}')
ctx.rule(u'NEW_VARIABLE',u'{NEW_VARIABLE}::{SIMPLE_VARIABLE}')

ctx.rule(u'MEMBER_NAME',u'{IDENTIFIER}')
ctx.rule(u'MEMBER_NAME',u'\\{{EXPR}\\}')
ctx.rule(u'MEMBER_NAME',u'{SIMPLE_VARIABLE}')

ctx.rule(u'PROPERTY_NAME',u'{T_STRING}')
ctx.rule(u'PROPERTY_NAME',u'\\{{EXPR}\\}')
ctx.rule(u'PROPERTY_NAME',u'{SIMPLE_VARIABLE}')

ctx.rule(u'ARRAY_PAIR_LIST',u'{NON_EMPTY_ARRAY_PAIR_LIST}')

ctx.rule(u'POSSIBLE_ARRAY_PAIR',u'')
ctx.rule(u'POSSIBLE_ARRAY_PAIR',u'{ARRAY_PAIR}')

ctx.rule(u'NON_EMPTY_ARRAY_PAIR_LIST',u'{NON_EMPTY_ARRAY_PAIR_LIST}, {POSSIBLE_ARRAY_PAIR}')
ctx.rule(u'NON_EMPTY_ARRAY_PAIR_LIST',u'{POSSIBLE_ARRAY_PAIR}')

ctx.rule(u'ARRAY_PAIR',u'{EXPR}=>{EXPR}')
ctx.rule(u'ARRAY_PAIR',u'{EXPR}')
ctx.rule(u'ARRAY_PAIR',u'{EXPR}=>&{VARIABLE}')
ctx.rule(u'ARRAY_PAIR',u'&{VARIABLE}')
ctx.rule(u'ARRAY_PAIR',u'{EXPR}=>list({ARRAY_PAIR_LIST})')
ctx.rule(u'ARRAY_PAIR',u'list({ARRAY_PAIR_LIST})')

ctx.rule(u'ENCAPS_LIST',u'{ENCAPS_LIST} {ENCAPS_VAR}')
ctx.rule(u'ENCAPS_LIST',u'{ENCAPS_VAR}')

ctx.rule(u'ENCAPS_VAR',u'{T_VARIABLE}')
ctx.rule(u'ENCAPS_VAR',u'{T_VARIABLE}[{ENCAPS_VAR_OFFSET}]')
ctx.rule(u'ENCAPS_VAR',u'{T_VARIABLE}->{T_STRING}')
ctx.rule(u'ENCAPS_VAR',u'$\\{{EXPR}\\}')
ctx.rule(u'ENCAPS_VAR',u'\\{${VARIABLE}\\}')

ctx.rule(u'ENCAPS_VAR_OFFSET',u'{T_STRING}')
ctx.rule(u'ENCAPS_VAR_OFFSET',u'{T_VARIABLE}')

ctx.rule(u'INTERNAL_FUNCTIONS_IN_YACC',u'isset({ISSET_VARIABLES}{POSSIBLE_COMMA})')
ctx.rule(u'INTERNAL_FUNCTIONS_IN_YACC',u'empty({EXPR})')
ctx.rule(u'INTERNAL_FUNCTIONS_IN_YACC',u'include {EXPR}')
ctx.rule(u'INTERNAL_FUNCTIONS_IN_YACC',u'include_once {EXPR}')
ctx.rule(u'INTERNAL_FUNCTIONS_IN_YACC',u'eval({EXPR})')
ctx.rule(u'INTERNAL_FUNCTIONS_IN_YACC',u'require {EXPR}')
ctx.rule(u'INTERNAL_FUNCTIONS_IN_YACC',u'require_once {EXPR}')

ctx.rule(u'ISSET_VARIABLES',u'{ISSET_VARIABLE}')
ctx.rule(u'ISSET_VARIABLES',u'{ISSET_VARIABLES}, {ISSET_VARIABLE}')

ctx.rule(u'ISSET_VARIABLE',u'{EXPR}')

############
############

ctx.rule(u'T_CONSTANT_ENCAPSED_STRING',u'"{STR_1}"')
ctx.rule(u'T_CONSTANT_ENCAPSED_STRING',u'\'{STR_2}\'')

ctx.rule(u'STR_1',u'')
ctx.rule(u'STR_1',u'{STR_1}{STR_1_CHAR}')

ctx.rule(u'STR_2',u'')
ctx.rule(u'STR_2',u'{STR_2}{STR_2_CHAR}')

ctx.rule(u'STR_1_CHAR',u'{DECIMALDIGIT}')
ctx.rule(u'STR_1_CHAR',u'{LETTER}')
ctx.rule(u'STR_1_CHAR',u'{CHAR}')
ctx.rule(u'STR_1_CHAR',u'\'')
ctx.rule(u'STR_1_CHAR',u'\\"')

ctx.rule(u'STR_2_CHAR',u'{DECIMALDIGIT}')
ctx.rule(u'STR_2_CHAR',u'{LETTER}')
ctx.rule(u'STR_2_CHAR',u'{CHAR}')
ctx.rule(u'STR_2_CHAR',u'"')
ctx.rule(u'STR_2_CHAR',u'\\\'')

ctx.rule(u'T_CLASS',u'class')
ctx.rule(u'T_CLASS',u'Class')

ctx.rule(u'T_VARIABLE',u'${T_STRING}')

ctx.rule(u'LNUMBER',u'{DECIMALDIGIT_SEQ}')
ctx.rule(u'LNUMBER',u'0x{HEX_SEQ}')

ctx.rule(u'DNUMBER',u'{DECIMALDIGIT_SEQ}.{DECIMALDIGIT_SEQ}{EXPONENT}{NUM_TYPE}')
ctx.rule(u'DNUMBER',u'{DECIMALDIGIT_SEQ}{E}{DECIMALDIGIT_SEQ}{NUM_TYPE}')

ctx.rule(u'DECIMALDIGIT_SEQ',u'{DECIMALDIGIT}')
ctx.rule(u'DECIMALDIGIT_SEQ',u'{DECIMALDIGIT_SEQ}{DECIMALDIGIT}')

ctx.rule(u'HEX_SEQ',u'{HEXD}')
ctx.rule(u'HEX_SEQ',u'{HEX_SEQ}{HEXD}')

ctx.rule(u'EXPONENT',u'')
ctx.rule(u'EXPONENT',u'{E}{DECIMALDIGIT_SEQ}')

ctx.rule(u'NUM_TYPE',u'')
ctx.rule(u'NUM_TYPE',u'f')
ctx.rule(u'NUM_TYPE',u'F')
ctx.rule(u'NUM_TYPE',u'd')
ctx.rule(u'NUM_TYPE',u'D')

ctx.rule(u'E',u'e')
ctx.rule(u'E',u'E')

ctx.rule(u'T_NS_SEPARATOR',u'\\')

ctx.rule(u'T_STRING',u'{INI_CHAR}{EXT_STRING}')

ctx.rule(u'INI_CHAR',u'{LETTER}')

ctx.rule(u'EXT_STRING',u'')
ctx.rule(u'EXT_STRING',u'{EXT_STRING}{LETTER}')
ctx.rule(u'EXT_STRING',u'{EXT_STRING}{DECIMALDIGIT}')

ctx.rule(u'DECIMALDIGIT',u'0')
ctx.rule(u'DECIMALDIGIT',u'1')
ctx.rule(u'DECIMALDIGIT',u'2')
ctx.rule(u'DECIMALDIGIT',u'3')
ctx.rule(u'DECIMALDIGIT',u'4')
ctx.rule(u'DECIMALDIGIT',u'5')
ctx.rule(u'DECIMALDIGIT',u'6')
ctx.rule(u'DECIMALDIGIT',u'7')
ctx.rule(u'DECIMALDIGIT',u'8')
ctx.rule(u'DECIMALDIGIT',u'9')

ctx.rule(u'HEXD',u'a')
ctx.rule(u'HEXD',u'b')
ctx.rule(u'HEXD',u'c')
ctx.rule(u'HEXD',u'd')
ctx.rule(u'HEXD',u'e')
ctx.rule(u'HEXD',u'f')
ctx.rule(u'HEXD',u'A')
ctx.rule(u'HEXD',u'B')
ctx.rule(u'HEXD',u'C')
ctx.rule(u'HEXD',u'D')
ctx.rule(u'HEXD',u'E')
ctx.rule(u'HEXD',u'F')
ctx.rule(u'HEXD',u'0')
ctx.rule(u'HEXD',u'1')
ctx.rule(u'HEXD',u'2')
ctx.rule(u'HEXD',u'3')
ctx.rule(u'HEXD',u'4')
ctx.rule(u'HEXD',u'5')
ctx.rule(u'HEXD',u'6')
ctx.rule(u'HEXD',u'7')
ctx.rule(u'HEXD',u'8')
ctx.rule(u'HEXD',u'9')

ctx.rule(u'LETTER',u'_')
ctx.rule(u'LETTER',u'a')
ctx.rule(u'LETTER',u'b')
ctx.rule(u'LETTER',u'c')
ctx.rule(u'LETTER',u'd')
ctx.rule(u'LETTER',u'e')
ctx.rule(u'LETTER',u'f')
ctx.rule(u'LETTER',u'g')
ctx.rule(u'LETTER',u'h')
ctx.rule(u'LETTER',u'i')
ctx.rule(u'LETTER',u'j')
ctx.rule(u'LETTER',u'k')
ctx.rule(u'LETTER',u'l')
ctx.rule(u'LETTER',u'm')
ctx.rule(u'LETTER',u'n')
ctx.rule(u'LETTER',u'o')
ctx.rule(u'LETTER',u'p')
ctx.rule(u'LETTER',u'q')
ctx.rule(u'LETTER',u'r')
ctx.rule(u'LETTER',u's')
ctx.rule(u'LETTER',u't')
ctx.rule(u'LETTER',u'u')
ctx.rule(u'LETTER',u'v')
ctx.rule(u'LETTER',u'w')
ctx.rule(u'LETTER',u'x')
ctx.rule(u'LETTER',u'y')
ctx.rule(u'LETTER',u'z')
ctx.rule(u'LETTER',u'A')
ctx.rule(u'LETTER',u'B')
ctx.rule(u'LETTER',u'C')
ctx.rule(u'LETTER',u'D')
ctx.rule(u'LETTER',u'E')
ctx.rule(u'LETTER',u'F')
ctx.rule(u'LETTER',u'G')
ctx.rule(u'LETTER',u'H')
ctx.rule(u'LETTER',u'I')
ctx.rule(u'LETTER',u'J')
ctx.rule(u'LETTER',u'K')
ctx.rule(u'LETTER',u'L')
ctx.rule(u'LETTER',u'M')
ctx.rule(u'LETTER',u'N')
ctx.rule(u'LETTER',u'O')
ctx.rule(u'LETTER',u'P')
ctx.rule(u'LETTER',u'Q')
ctx.rule(u'LETTER',u'R')
ctx.rule(u'LETTER',u'S')
ctx.rule(u'LETTER',u'T')
ctx.rule(u'LETTER',u'U')
ctx.rule(u'LETTER',u'V')
ctx.rule(u'LETTER',u'W')
ctx.rule(u'LETTER',u'X')
ctx.rule(u'LETTER',u'Y')
ctx.rule(u'LETTER',u'Z')

ctx.rule(u'CHAR',u'\x00')
ctx.rule(u'CHAR',u'\x01')
ctx.rule(u'CHAR',u'\x02')
ctx.rule(u'CHAR',u'\x03')
ctx.rule(u'CHAR',u'\x04')
ctx.rule(u'CHAR',u'\x05')
ctx.rule(u'CHAR',u'\x06')
ctx.rule(u'CHAR',u'\x07')
ctx.rule(u'CHAR',u'\x08')
ctx.rule(u'CHAR',u'\x09')
ctx.rule(u'CHAR',u'\x0A')
ctx.rule(u'CHAR',u'\x0B')
ctx.rule(u'CHAR',u'\x0C')
ctx.rule(u'CHAR',u'\x0D')
ctx.rule(u'CHAR',u'\x0E')
ctx.rule(u'CHAR',u'\x0F')
ctx.rule(u'CHAR',u'\x10')
ctx.rule(u'CHAR',u'\x11')
ctx.rule(u'CHAR',u'\x12')
ctx.rule(u'CHAR',u'\x13')
ctx.rule(u'CHAR',u'\x14')
ctx.rule(u'CHAR',u'\x15')
ctx.rule(u'CHAR',u'\x16')
ctx.rule(u'CHAR',u'\x17')
ctx.rule(u'CHAR',u'\x18')
ctx.rule(u'CHAR',u'\x19')
ctx.rule(u'CHAR',u'\x1A')
ctx.rule(u'CHAR',u'\x1B')
ctx.rule(u'CHAR',u'\x1C')
ctx.rule(u'CHAR',u'\x1D')
ctx.rule(u'CHAR',u'\x1E')
ctx.rule(u'CHAR',u'\x1F')
ctx.rule(u'CHAR',u'\x20')
ctx.rule(u'CHAR',u'\x21')
ctx.rule(u'CHAR',u'\x23')
ctx.rule(u'CHAR',u'\x24')
ctx.rule(u'CHAR',u'\x25')
ctx.rule(u'CHAR',u'\x26')
ctx.rule(u'CHAR',u'\x28')
ctx.rule(u'CHAR',u'\x29')
ctx.rule(u'CHAR',u'\x2A')
ctx.rule(u'CHAR',u'\x2B')
ctx.rule(u'CHAR',u'\x2C')
ctx.rule(u'CHAR',u'\x2D')
ctx.rule(u'CHAR',u'\x2E')
ctx.rule(u'CHAR',u'\x2F')
ctx.rule(u'CHAR',u'\x3A')
ctx.rule(u'CHAR',u'\x3B')
ctx.rule(u'CHAR',u'\x3C')
ctx.rule(u'CHAR',u'\x3D')
ctx.rule(u'CHAR',u'\x3E')
ctx.rule(u'CHAR',u'\x3F')
ctx.rule(u'CHAR',u'\x40')
ctx.rule(u'CHAR',u'\x5B')
ctx.rule(u'CHAR',u'\x5C')
ctx.rule(u'CHAR',u'\x5D')
ctx.rule(u'CHAR',u'\x5E')
ctx.rule(u'CHAR',u'\x60')
ctx.rule(u'CHAR',u'\x7B')
ctx.rule(u'CHAR',u'\x7C')
ctx.rule(u'CHAR',u'\x7D')
ctx.rule(u'CHAR',u'\x7E')
ctx.rule(u'CHAR',u'\x7F')
