ctx.rule(u'START',u'{PROGRAM}')

ctx.rule(u'PROGRAM', u'{COMPSTMT}')

ctx.rule(u'COMPSTMT', u'\n{STMT}{TERM_EXPR_REP}{TERM_OPT}\n')

ctx.rule(u'STMT', u'{CALL} do {BLOCK_VAR_OPT}{COMPSTMT}end')
ctx.rule(u'STMT', u'undef {FNAME}')
ctx.rule(u'STMT', u'alias {FNAME} {FNAME}')
ctx.rule(u'STMT', u'{STMT} if {EXPR}')
ctx.rule(u'STMT', u'{STMT} while {EXPR}')
ctx.rule(u'STMT', u'{STMT} unless {EXPR}')
ctx.rule(u'STMT', u'{STMT} until {EXPR}')
ctx.rule(u'STMT', u'begin \\{{COMPSTMT}\\}')
ctx.rule(u'STMT', u'end \\{{COMPSTMT}\\}')
ctx.rule(u'STMT', u'{LHS} = {COMMAND} do {BLOCK_VAR_OPT}{COMPSTMT}end')
ctx.rule(u'STMT', u'{LHS} = {COMMAND}')
ctx.rule(u'STMT', u'{EXPR}')

ctx.rule(u'EXPR', u'{MLHS} = {MRHS}')
ctx.rule(u'EXPR', u'return {CALL_ARGS}')
ctx.rule(u'EXPR', u'yield {CALL_ARGS}')
ctx.rule(u'EXPR', u'{EXPR} and {EXPR}')
ctx.rule(u'EXPR', u'{EXPR} or {EXPR}')
ctx.rule(u'EXPR', u'not {EXPR}')
ctx.rule(u'EXPR', u'{COMMAND}')
ctx.rule(u'EXPR', u'! {COMMAND}')
ctx.rule(u'EXPR', u'{ARG}')

ctx.rule(u'CALL', u'{FUNCTION}')
ctx.rule(u'CALL', u'{COMMAND}')

ctx.rule(u'COMMAND', u'{OPERATION} {CALL_ARGS}')
ctx.rule(u'COMMAND', u'{PRIMARY}.{OPERATION} {CALL_ARGS}')
ctx.rule(u'COMMAND', u'{PRIMARY}::{OPERATION} {CALL_ARGS}')
ctx.rule(u'COMMAND', u'super {CALL_ARGS}')

ctx.rule(u'FUNCTION', u'{OPERATION}{CALL_ARGS_BRACKETS_OPT}')
ctx.rule(u'FUNCTION', u'{PRIMARY}.{OPERATION}({CALL_ARGS_OPT})')
ctx.rule(u'FUNCTION', u'{PRIMARY}::{OPERATION}({CALL_ARGS_OPT})')
ctx.rule(u'FUNCTION', u'{PRIMARY}.{OPERATION}')
ctx.rule(u'FUNCTION', u'{PRIMARY}::{OPERATION}')
ctx.rule(u'FUNCTION', u'super({CALL_ARGS_OPT})')
ctx.rule(u'FUNCTION', u'super')

ctx.rule(u'ARG', u'{LHS} = {ARG}')
ctx.rule(u'ARG', u'{LHS} {OP_ASGN} {ARG}')
ctx.rule(u'ARG', u'{ARG} {OP_BIN} {ARG}')
ctx.rule(u'ARG', u'+ {ARG}')
ctx.rule(u'ARG', u'- {ARG}')
ctx.rule(u'ARG', u'! {ARG}')
ctx.rule(u'ARG', u'~ {ARG}')
ctx.rule(u'ARG', u'defined? {ARG}')
ctx.rule(u'ARG', u'{PRIMARY}')

ctx.rule(u'PRIMARY', u'({COMPSTMT})')
ctx.rule(u'PRIMARY', u'{LITERAL}')
ctx.rule(u'PRIMARY', u'{VARIABLE}')
ctx.rule(u'PRIMARY', u'{PRIMARY}::{IDENTIFIER}')
ctx.rule(u'PRIMARY', u'::{IDENTIFIER}')
ctx.rule(u'PRIMARY', u'{PRIMARY} [{ARGS_OPT}]')
ctx.rule(u'PRIMARY', u'[{ARGS_COMMA_OPT}]')
ctx.rule(u'PRIMARY', u'\\{{ARGS_ASSOCS_COMMA_OPT}\\}')
ctx.rule(u'PRIMARY', u'return {CALL_ARGS_BRACKETS_OPT}')
ctx.rule(u'PRIMARY', u'yield {CALL_ARGS_BRACKETS_OPT}')
ctx.rule(u'PRIMARY', u'defined?({ARG})')
ctx.rule(u'PRIMARY', u'{FUNCTION}')
ctx.rule(u'PRIMARY', u'{FUNCTION} \\{{BLOCK_VAR_OPT} {COMPSTMT}\\}\n')
ctx.rule(u'PRIMARY', u'if {EXPR} {THEN}{COMPSTMT}{ELSIF_REP}{ELSE_OPT}end\n')
ctx.rule(u'PRIMARY', u'unless {EXPR} {THEN}{COMPSTMT}{ELSE_OPT}end\n')
ctx.rule(u'PRIMARY', u'while {EXPR} {DO}{COMPSTMT}end\n')
ctx.rule(u'PRIMARY', u'until {EXPR} {DO}{COMPSTMT}end\n')
ctx.rule(u'PRIMARY', u'case{COMPSTMT}{WHEN_REP}{ELSE_OPT}end\n')
ctx.rule(u'PRIMARY', u'for {BLOCK_VAR} in {EXPR} {DO}{COMPSTMT}end\n')
ctx.rule(u'PRIMARY', u'begin{COMPSTMT}{RESCUE_REP}{ELSE_OPT}{ENSURE_OPT}end\n')
ctx.rule(u'PRIMARY', u'class {IDENTIFIER} {INHERITANCE_OPT}{COMPSTMT}end\n')
ctx.rule(u'PRIMARY', u'module {IDENTIFIER}{COMPSTMT}end\n')
ctx.rule(u'PRIMARY', u'def {FNAME} {ARGDECL}{COMPSTMT}end\n')
ctx.rule(u'PRIMARY', u'def {SINGLETON}{DOTS}{FNAME} {ARGDECL}{COMPSTMT}end\n')

ctx.rule(u'WHEN_REP', u'when {MRHS} {THEN}{COMPSTMT}')
ctx.rule(u'WHEN_REP', u'when {MRHS} {THEN}{COMPSTMT}{WHEN_REP}')

ctx.rule(u'THEN', u'{TERM}')
ctx.rule(u'THEN', u'then')
ctx.rule(u'THEN', u'{TERM} then')

ctx.rule(u'DO', u'{TERM}')
ctx.rule(u'DO', u'do')
ctx.rule(u'DO', u'{TERM} do')

ctx.rule(u'BLOCK_VAR', u'{LHS}')
ctx.rule(u'BLOCK_VAR', u'{MLHS}')

ctx.rule(u'MLHS', u'{MLHS_ITEM}, {MLHS_ITEM_OPT} * {LHS}')
ctx.rule(u'MLHS', u'{MLHS_ITEM}, {MLHS_ITEM_OPT} *')
ctx.rule(u'MLHS', u'{MLHS_ITEM}, {MLHS_ITEM_OPT}')
ctx.rule(u'MLHS', u'* {LHS}')

ctx.rule(u'MLHS_ITEM', u'{LHS}')
ctx.rule(u'MLHS_ITEM', u'({MLHS})')

ctx.rule(u'LHS', u'{PRIMARY} [{ARGS_OPT}]')
ctx.rule(u'LHS', u'{PRIMARY}.{IDENTIFIER}')
ctx.rule(u'LHS', u'{VARIABLE}')

ctx.rule(u'MRHS', u'{ARGS}{ARG_AST_OPT}')
ctx.rule(u'MRHS', u'* {ARG}')

ctx.rule(u'CALL_ARGS', u'{ARGS}')
ctx.rule(u'CALL_ARGS', u'{ARGS}{ASSOCS_OPT}{ARG_AST_OPT}{ARG_AMP_OPT}')
ctx.rule(u'CALL_ARGS', u'{ASSOCS}{ARG_AST_OPT}{ARG_AMP_OPT}')
ctx.rule(u'CALL_ARGS', u'*{ARG}{ARG_AMP_OPT}')
ctx.rule(u'CALL_ARGS', u'&{ARG}')
ctx.rule(u'CALL_ARGS', u'{COMMAND}')

ctx.rule(u'ARGS', u'{ARG}, {ARGS}')
ctx.rule(u'ARGS', u'{ARG}')

ctx.rule(u'ARGDECL', u'({ARGLIST})')
ctx.rule(u'ARGDECL', u'{ARGLIST}{TERM}')

ctx.rule(u'ARGLIST', u'{IDENTIFIER}{IDENTIFIER_REP}{IDENTIFIER_AST_OPT}{IDENTIFIER_AMP_OPT}')
ctx.rule(u'ARGLIST', u'*{IDENTIFIER}{IDENTIFIER_AMP_OPT}')
ctx.rule(u'ARGLIST', u'&{IDENTIFIER}')
ctx.rule(u'ARGLIST', u'')

ctx.rule(u'SINGLETON', u'{VARIABLE}')
ctx.rule(u'SINGLETON', u'({EXPR})')

ctx.rule(u'ASSOCS', u'{ASSOC}, {ASSOCS}')
ctx.rule(u'ASSOCS', u'{ASSOC}')

ctx.rule(u'ASSOC', u'{ARG} => {ARG}')

ctx.rule(u'VARIABLE', u'{VARNAME}')
ctx.rule(u'VARIABLE', u'nil')
ctx.rule(u'VARIABLE', u'self')

ctx.rule(u'LITERAL', u'{NUMERIC}')
ctx.rule(u'LITERAL', u'{SYMBOL}')
ctx.rule(u'LITERAL', u'{STRING}')
ctx.rule(u'LITERAL', u'{STRING2}')
ctx.rule(u'LITERAL', u'{HERE_DOC}')
ctx.rule(u'LITERAL', u'{REGEXP}')

ctx.rule(u'TERM_OPT', u'{TERM}')
ctx.rule(u'TERM_OPT', u'')

ctx.rule(u'TERM', u';')
ctx.rule(u'TERM', u'\n')


#### Auxiliary rules

ctx.rule(u'TERM_EXPR_REP', u'{TERM}\n{EXPR}{TERM_EXPR_REP}')
ctx.rule(u'TERM_EXPR_REP', u'')

ctx.rule(u'BLOCK_VAR_OPT', u'| {BLOCK_VAR} |')
ctx.rule(u'BLOCK_VAR_OPT', u'| |')
ctx.rule(u'BLOCK_VAR_OPT', u'')

ctx.rule(u'ARG_AST_OPT', u',*{ARG}')
ctx.rule(u'ARG_AST_OPT', u'')

ctx.rule(u'ARG_AMP_OPT', u',&{ARG}')
ctx.rule(u'ARG_AMP_OPT', u'')

ctx.rule(u'ARG_AMP_OPT', u',&{ARG}')
ctx.rule(u'ARG_AMP_OPT', u'')

ctx.rule(u'ASSOCS_OPT', u', {ASSOCS}')
ctx.rule(u'ASSOCS_OPT', u'')

ctx.rule(u'CALL_ARGS_BRACKETS_OPT', u'({CALL_ARGS_OPT})')
ctx.rule(u'CALL_ARGS_BRACKETS_OPT', u'')

ctx.rule(u'CALL_ARGS_OPT', u'{CALL_ARGS}')
ctx.rule(u'CALL_ARGS_OPT', u'')

ctx.rule(u'ARGS_OPT', u'{ARGS}')
ctx.rule(u'ARGS_OPT', u'')

ctx.rule(u'ARGS_COMMA_OPT', u'{ARGS}{COMMA_OPT}')
ctx.rule(u'ARGS_COMMA_OPT', u'')

ctx.rule(u'COMMA_OPT', u',')
ctx.rule(u'COMMA_OPT', u'')

ctx.rule(u'ARGS_ASSOCS_COMMA_OPT', u'{ARGS}')
ctx.rule(u'ARGS_ASSOCS_COMMA_OPT', u'{ASSOCS}{COMMA_OPT}')
ctx.rule(u'ARGS_ASSOCS_COMMA_OPT', u'')

ctx.rule(u'ELSIF_REP', u'\nelsif {EXPR} {THEN}{COMPSTMT}{ELSIF_REP}')
ctx.rule(u'ELSIF_REP', u'')

ctx.rule(u'ELSE_OPT', u'\nelse{COMPSTMT}')
ctx.rule(u'ELSE_OPT', u'')

ctx.rule(u'INHERITANCE_OPT', u'< {IDENTIFIER}')
ctx.rule(u'INHERITANCE_OPT', u'')

ctx.rule(u'RESCUE_REP', u'\nrescue {ARGS_OPT} {DO}{COMPSTMT}{RESCUE_REP}')
ctx.rule(u'RESCUE_REP', u'')

ctx.rule(u'ENSURE_OPT', u'\nensure{COMPSTMT}')
ctx.rule(u'ENSURE_OPT', u'')

ctx.rule(u'DOTS', u'.')
ctx.rule(u'DOTS', u'::')

ctx.rule(u'MLHS_ITEM_OPT', u'{MLHS_ITEM_REP}')
ctx.rule(u'MLHS_ITEM_OPT', u'')

ctx.rule(u'MLHS_ITEM_REP', u'{MLHS_ITEM}, {MLHS_ITEM_REP}')
ctx.rule(u'MLHS_ITEM_REP', u'{MLHS_ITEM}')

ctx.rule(u'IDENTIFIER_AST_OPT', u',*{IDENTIFIER}')
ctx.rule(u'IDENTIFIER_AST_OPT', u'')

ctx.rule(u'IDENTIFIER_AMP_OPT', u',&{IDENTIFIER}')
ctx.rule(u'IDENTIFIER_AMP_OPT', u'')

ctx.rule(u'IDENTIFIER_REP', u', {IDENTIFIER}{IDENTIFIER_REP}')
ctx.rule(u'IDENTIFIER_REP', u'')

ctx.rule(u'VARNAME', u'{GLOBAL}')
ctx.rule(u'VARNAME', u'@{IDENTIFIER}')
ctx.rule(u'VARNAME', u'{IDENTIFIER}')

#### Lex rules

ctx.rule(u'OP_ASGN', u'+=')
ctx.rule(u'OP_ASGN', u'-=')
ctx.rule(u'OP_ASGN', u'*=')
ctx.rule(u'OP_ASGN', u'/=')
ctx.rule(u'OP_ASGN', u'%=')
ctx.rule(u'OP_ASGN', u'**=')
ctx.rule(u'OP_ASGN', u'&=')
ctx.rule(u'OP_ASGN', u'|=')
ctx.rule(u'OP_ASGN', u'^=')
ctx.rule(u'OP_ASGN', u'<<=')
ctx.rule(u'OP_ASGN', u'>>=')
ctx.rule(u'OP_ASGN', u'&&=')
ctx.rule(u'OP_ASGN', u'||=')

ctx.rule(u'OP_BIN', u'..')
ctx.rule(u'OP_BIN', u'...')
ctx.rule(u'OP_BIN', u'+')
ctx.rule(u'OP_BIN', u'-')
ctx.rule(u'OP_BIN', u'*')
ctx.rule(u'OP_BIN', u'/')
ctx.rule(u'OP_BIN', u'%')
ctx.rule(u'OP_BIN', u'**')
ctx.rule(u'OP_BIN', u'|')
ctx.rule(u'OP_BIN', u'^')
ctx.rule(u'OP_BIN', u'&')
ctx.rule(u'OP_BIN', u'<=>')
ctx.rule(u'OP_BIN', u'>')
ctx.rule(u'OP_BIN', u'>=')
ctx.rule(u'OP_BIN', u'<')
ctx.rule(u'OP_BIN', u'<=')
ctx.rule(u'OP_BIN', u'==')
ctx.rule(u'OP_BIN', u'===')
ctx.rule(u'OP_BIN', u'!=')
ctx.rule(u'OP_BIN', u'=~')
ctx.rule(u'OP_BIN', u'!~')
ctx.rule(u'OP_BIN', u'<<')
ctx.rule(u'OP_BIN', u'>>')
ctx.rule(u'OP_BIN', u'&&')
ctx.rule(u'OP_BIN', u'||')

ctx.rule(u'FNAME_OP', u'..')
ctx.rule(u'FNAME_OP', u'|')
ctx.rule(u'FNAME_OP', u'^')
ctx.rule(u'FNAME_OP', u'&')
ctx.rule(u'FNAME_OP', u'<=>')
ctx.rule(u'FNAME_OP', u'==')
ctx.rule(u'FNAME_OP', u'===')
ctx.rule(u'FNAME_OP', u'=~')
ctx.rule(u'FNAME_OP', u'>')
ctx.rule(u'FNAME_OP', u'>=')
ctx.rule(u'FNAME_OP', u'<')
ctx.rule(u'FNAME_OP', u'<=')
ctx.rule(u'FNAME_OP', u'+')
ctx.rule(u'FNAME_OP', u'-')
ctx.rule(u'FNAME_OP', u'*')
ctx.rule(u'FNAME_OP', u'/')
ctx.rule(u'FNAME_OP', u'%')
ctx.rule(u'FNAME_OP', u'**')
ctx.rule(u'FNAME_OP', u'<<')
ctx.rule(u'FNAME_OP', u'>>')
ctx.rule(u'FNAME_OP', u'~')
ctx.rule(u'FNAME_OP', u'+@')
ctx.rule(u'FNAME_OP', u'-@')
ctx.rule(u'FNAME_OP', u'[]')
ctx.rule(u'FNAME_OP', u'[]=')

ctx.rule(u'SYMBOL', u':{FNAME}')
ctx.rule(u'SYMBOL', u':{VARNAME}')

ctx.rule(u'FNAME', u'{IDENTIFIER}')
ctx.rule(u'FNAME', u'{FNAME_OP}')

ctx.rule(u'OPERATION', u'{IDENTIFIER}')
ctx.rule(u'OPERATION', u'{IDENTIFIER}!')
ctx.rule(u'OPERATION', u'{IDENTIFIER}?')

ctx.rule(u'GLOBAL', u'${IDENTIFIER}')
ctx.rule(u'GLOBAL', u'${ANY_CHAR}')
ctx.rule(u'GLOBAL', u'$-{ANY_CHAR}')

ctx.rule(u'STRING', u'"{STR_1}"')
ctx.rule(u'STRING', u'\'{STR_2}\'')
ctx.rule(u'STRING', u'`{STR_3}`')

ctx.rule(u'STR_1',u'')
ctx.rule(u'STR_1',u'{STR_1}{STR_1_CHAR}')

ctx.rule(u'STR_2',u'')
ctx.rule(u'STR_2',u'{STR_2}{STR_2_CHAR}')

ctx.rule(u'STR_3',u'')
ctx.rule(u'STR_3',u'{STR_3}{STR_3_CHAR}')

ctx.rule(u'STR_1_CHAR',u'{CHAR}')
ctx.rule(u'STR_1_CHAR', u'{BRACKET}')
ctx.rule(u'STR_1_CHAR', u'/')
ctx.rule(u'STR_1_CHAR',u'\\"')
ctx.rule(u'STR_1_CHAR',u'\'')
ctx.rule(u'STR_1_CHAR',u'`')

ctx.rule(u'STR_2_CHAR',u'{CHAR}')
ctx.rule(u'STR_2_CHAR', u'{BRACKET}')
ctx.rule(u'STR_2_CHAR', u'/')
ctx.rule(u'STR_2_CHAR',u'"')
ctx.rule(u'STR_2_CHAR',u'\\\'')
ctx.rule(u'STR_2_CHAR',u'`')

ctx.rule(u'STR_3_CHAR',u'{CHAR}')
ctx.rule(u'STR_3_CHAR', u'{BRACKET}')
ctx.rule(u'STR_3_CHAR', u'/')
ctx.rule(u'STR_3_CHAR',u'"')
ctx.rule(u'STR_3_CHAR',u'\'')
ctx.rule(u'STR_3_CHAR',u'\\`')

ctx.rule(u'STRING2', u'{STRING2_PREFIX}\\{{STRING2_1}\\}')
ctx.rule(u'STRING2', u'{STRING2_PREFIX}[{STRING2_2}]')
ctx.rule(u'STRING2', u'{STRING2_PREFIX}({STRING2_3})')

ctx.rule(u'STRING2_PREFIX', u'%Q')
ctx.rule(u'STRING2_PREFIX', u'%q')
ctx.rule(u'STRING2_PREFIX', u'%x')

ctx.rule(u'HERE_DOC', u'<<EOF\n{ANY_STRING}\nEOF')

ctx.rule(u'REGEXP', u'/{REGEXP_STR_1}/i')
ctx.rule(u'REGEXP', u'/{REGEXP_STR_1}/o')
ctx.rule(u'REGEXP', u'/{REGEXP_STR_1}/p')
ctx.rule(u'REGEXP', u'%r\\{{STRING2_1}\\}')
ctx.rule(u'REGEXP', u'%r[{STRING2_2}]')

ctx.rule(u'REGEXP_STR_1',u'')
ctx.rule(u'REGEXP_STR_1',u'{REGEXP_STR_1}{REGEXP_STR_1_CHAR}')

ctx.rule(u'REGEXP_STR_1_CHAR',u'{CHAR}')
ctx.rule(u'REGEXP_STR_1_CHAR', u'{BRACKET}')
ctx.rule(u'REGEXP_STR_1_CHAR', u'{QUOTE}')
ctx.rule(u'REGEXP_STR_1_CHAR', u'\\/')

ctx.rule(u'STRING2_1', u'{STRING2_1}{STRING2_1_CHAR}')
ctx.rule(u'STRING2_1', u'')

ctx.rule(u'STRING2_2', u'{STRING2_2}{STRING2_2_CHAR}')
ctx.rule(u'STRING2_2', u'')

ctx.rule(u'STRING2_3', u'{STRING2_3}{STRING2_3_CHAR}')
ctx.rule(u'STRING2_3', u'')

ctx.rule(u'STRING2_1_CHAR',u'{CHAR}')
ctx.rule(u'STRING2_1_CHAR', u'{QUOTE}')
ctx.rule(u'STRING2_1_CHAR', u'/')
ctx.rule(u'STRING2_1_CHAR', u'\\\\{')
ctx.rule(u'STRING2_1_CHAR', u'\\\\}')
ctx.rule(u'STRING2_1_CHAR', u'(')
ctx.rule(u'STRING2_1_CHAR', u')')
ctx.rule(u'STRING2_1_CHAR', u'[')
ctx.rule(u'STRING2_1_CHAR', u']')

ctx.rule(u'STRING2_2_CHAR',u'{CHAR}')
ctx.rule(u'STRING2_2_CHAR', u'{QUOTE}')
ctx.rule(u'STRING2_2_CHAR', u'/')
ctx.rule(u'STRING2_2_CHAR', u'\\{')
ctx.rule(u'STRING2_2_CHAR', u'\\}')
ctx.rule(u'STRING2_2_CHAR', u'(')
ctx.rule(u'STRING2_2_CHAR', u')')
ctx.rule(u'STRING2_2_CHAR', u'\\[')
ctx.rule(u'STRING2_2_CHAR', u'\\]')

ctx.rule(u'STRING2_3_CHAR',u'{CHAR}')
ctx.rule(u'STRING2_3_CHAR', u'{QUOTE}')
ctx.rule(u'STRING2_3_CHAR', u'/')
ctx.rule(u'STRING2_3_CHAR', u'\\{')
ctx.rule(u'STRING2_3_CHAR', u'\\}')
ctx.rule(u'STRING2_3_CHAR', u'\\(')
ctx.rule(u'STRING2_3_CHAR', u'\\)')
ctx.rule(u'STRING2_3_CHAR', u'[')
ctx.rule(u'STRING2_3_CHAR', u']')

# .*
ctx.rule(u'ANY_STRING', u'{ANY_CHAR}{ANY_STRING}')
ctx.rule(u'ANY_STRING', u'')

# [a-zA-Z_][a-zA-Z0-9_]*
ctx.rule(u'IDENTIFIER', u'{LETTER}{EXT_STRING}')

ctx.rule(u'EXT_STRING',u'')
ctx.rule(u'EXT_STRING',u'{EXT_STRING}{LETTER}')
ctx.rule(u'EXT_STRING',u'{EXT_STRING}{DECIMALDIGIT}')

ctx.rule(u'NUMERIC',u'{HEX}')
ctx.rule(u'NUMERIC',u'{DECIMAL}')

# 0[xX][0-9a-fA-F]+(\.[0-9a-fA-F]+)?([pP]-?[0-9a-fA-F]+)?
ctx.rule(u'HEX',u'{HEX_PREFIX}{HEX_SEQ}{HEX_FLOAT_SEQ}{HEX_FLOAT_EXP}')

ctx.rule(u'HEX_PREFIX',u'0x')
ctx.rule(u'HEX_PREFIX',u'0X')

ctx.rule(u'HEX_SEQ',u'{HEXD}{HEX_SEQ}')
ctx.rule(u'HEX_SEQ',u'{HEXD}')

ctx.rule(u'HEX_FLOAT_SEQ',u'.{HEX_SEQ}')
ctx.rule(u'HEX_FLOAT_SEQ',u'')

ctx.rule(u'HEX_FLOAT_EXP',u'{HEX_FLOAT_EXP_PREFIX}{HEX_SEQ}')
ctx.rule(u'HEX_FLOAT_EXP',u'')

ctx.rule(u'HEX_FLOAT_EXP_PREFIX',u'p')
ctx.rule(u'HEX_FLOAT_EXP_PREFIX',u'p-')
ctx.rule(u'HEX_FLOAT_EXP_PREFIX',u'P')
ctx.rule(u'HEX_FLOAT_EXP_PREFIX',u'P-')

ctx.rule(u'ANY_CHAR', u'{CHAR}')
ctx.rule(u'ANY_CHAR', u'{BRACKET}')
ctx.rule(u'ANY_CHAR', u'{QUOTE}')
ctx.rule(u'ANY_CHAR', u'/')

# [-+]?([0-9]+(\.[0-9]+)?([eE]-?[0-9]+)?)
ctx.rule(u'DECIMAL',u'{DEC_PREFIX}{DEC_SEQ}{DEC_FLOAT_SEQ}{DEC_FLOAT_EXP}')

ctx.rule(u'DEC_PREFIX',u'-')
ctx.rule(u'DEC_PREFIX',u'+')
ctx.rule(u'DEC_PREFIX',u'')

ctx.rule(u'DEC_SEQ',u'{DECIMALDIGIT}{DEC_SEQ}')
ctx.rule(u'DEC_SEQ',u'{DECIMALDIGIT}')

ctx.rule(u'DEC_FLOAT_SEQ',u'.{DEC_SEQ}')
ctx.rule(u'DEC_FLOAT_SEQ',u'')

ctx.rule(u'DEC_FLOAT_EXP',u'{DEC_FLOAT_EXP_PREFIX}{DEC_SEQ}')
ctx.rule(u'DEC_FLOAT_EXP',u'')

ctx.rule(u'DEC_FLOAT_EXP_PREFIX',u'e')
ctx.rule(u'DEC_FLOAT_EXP_PREFIX',u'e-')
ctx.rule(u'DEC_FLOAT_EXP_PREFIX',u'E')
ctx.rule(u'DEC_FLOAT_EXP_PREFIX',u'E-')

ctx.rule(u'DECIMALDIGIT',u'0')
ctx.rule(u'DECIMALDIGIT',u'1')
ctx.rule(u'DECIMALDIGIT',u'2')
ctx.rule(u'DECIMALDIGIT',u'3')
ctx.rule(u'DECIMALDIGIT',u'4')
ctx.rule(u'DECIMALDIGIT',u'5')
ctx.rule(u'DECIMALDIGIT',u'6')
ctx.rule(u'DECIMALDIGIT',u'7')
ctx.rule(u'DECIMALDIGIT',u'8')
ctx.rule(u'DECIMALDIGIT',u'9')

ctx.rule(u'HEXD',u'a')
ctx.rule(u'HEXD',u'b')
ctx.rule(u'HEXD',u'c')
ctx.rule(u'HEXD',u'd')
ctx.rule(u'HEXD',u'e')
ctx.rule(u'HEXD',u'f')
ctx.rule(u'HEXD',u'A')
ctx.rule(u'HEXD',u'B')
ctx.rule(u'HEXD',u'C')
ctx.rule(u'HEXD',u'D')
ctx.rule(u'HEXD',u'E')
ctx.rule(u'HEXD',u'F')
ctx.rule(u'HEXD',u'0')
ctx.rule(u'HEXD',u'1')
ctx.rule(u'HEXD',u'2')
ctx.rule(u'HEXD',u'3')
ctx.rule(u'HEXD',u'4')
ctx.rule(u'HEXD',u'5')
ctx.rule(u'HEXD',u'6')
ctx.rule(u'HEXD',u'7')
ctx.rule(u'HEXD',u'8')
ctx.rule(u'HEXD',u'9')

ctx.rule(u'LETTER',u'_')
ctx.rule(u'LETTER',u'a')
ctx.rule(u'LETTER',u'b')
ctx.rule(u'LETTER',u'c')
ctx.rule(u'LETTER',u'd')
ctx.rule(u'LETTER',u'e')
ctx.rule(u'LETTER',u'f')
ctx.rule(u'LETTER',u'g')
ctx.rule(u'LETTER',u'h')
ctx.rule(u'LETTER',u'i')
ctx.rule(u'LETTER',u'j')
ctx.rule(u'LETTER',u'k')
ctx.rule(u'LETTER',u'l')
ctx.rule(u'LETTER',u'm')
ctx.rule(u'LETTER',u'n')
ctx.rule(u'LETTER',u'o')
ctx.rule(u'LETTER',u'p')
ctx.rule(u'LETTER',u'q')
ctx.rule(u'LETTER',u'r')
ctx.rule(u'LETTER',u's')
ctx.rule(u'LETTER',u't')
ctx.rule(u'LETTER',u'u')
ctx.rule(u'LETTER',u'v')
ctx.rule(u'LETTER',u'w')
ctx.rule(u'LETTER',u'x')
ctx.rule(u'LETTER',u'y')
ctx.rule(u'LETTER',u'z')
ctx.rule(u'LETTER',u'A')
ctx.rule(u'LETTER',u'B')
ctx.rule(u'LETTER',u'C')
ctx.rule(u'LETTER',u'D')
ctx.rule(u'LETTER',u'E')
ctx.rule(u'LETTER',u'F')
ctx.rule(u'LETTER',u'G')
ctx.rule(u'LETTER',u'H')
ctx.rule(u'LETTER',u'I')
ctx.rule(u'LETTER',u'J')
ctx.rule(u'LETTER',u'K')
ctx.rule(u'LETTER',u'L')
ctx.rule(u'LETTER',u'M')
ctx.rule(u'LETTER',u'N')
ctx.rule(u'LETTER',u'O')
ctx.rule(u'LETTER',u'P')
ctx.rule(u'LETTER',u'Q')
ctx.rule(u'LETTER',u'R')
ctx.rule(u'LETTER',u'S')
ctx.rule(u'LETTER',u'T')
ctx.rule(u'LETTER',u'U')
ctx.rule(u'LETTER',u'V')
ctx.rule(u'LETTER',u'W')
ctx.rule(u'LETTER',u'X')
ctx.rule(u'LETTER',u'Y')
ctx.rule(u'LETTER',u'Z')

ctx.rule(u'BRACKET',u'(')
ctx.rule(u'BRACKET',u')')
ctx.rule(u'BRACKET',u'[')
ctx.rule(u'BRACKET',u']')
ctx.rule(u'BRACKET',u'\\{')
ctx.rule(u'BRACKET',u'\\}')

ctx.rule(u'QUOTE',u'"')
ctx.rule(u'QUOTE',u'\'')
ctx.rule(u'QUOTE',u'`')

# All ASCII characters except: ' " ` () [] {} /
ctx.rule(u'CHAR',u'\x00')
ctx.rule(u'CHAR',u'\x01')
ctx.rule(u'CHAR',u'\x02')
ctx.rule(u'CHAR',u'\x03')
ctx.rule(u'CHAR',u'\x04')
ctx.rule(u'CHAR',u'\x05')
ctx.rule(u'CHAR',u'\x06')
ctx.rule(u'CHAR',u'\x07')
ctx.rule(u'CHAR',u'\x08')
ctx.rule(u'CHAR',u'\x09')
ctx.rule(u'CHAR',u'\x0A')
ctx.rule(u'CHAR',u'\x0B')
ctx.rule(u'CHAR',u'\x0C')
ctx.rule(u'CHAR',u'\x0D')
ctx.rule(u'CHAR',u'\x0E')
ctx.rule(u'CHAR',u'\x0F')
ctx.rule(u'CHAR',u'\x10')
ctx.rule(u'CHAR',u'\x11')
ctx.rule(u'CHAR',u'\x12')
ctx.rule(u'CHAR',u'\x13')
ctx.rule(u'CHAR',u'\x14')
ctx.rule(u'CHAR',u'\x15')
ctx.rule(u'CHAR',u'\x16')
ctx.rule(u'CHAR',u'\x17')
ctx.rule(u'CHAR',u'\x18')
ctx.rule(u'CHAR',u'\x19')
ctx.rule(u'CHAR',u'\x1A')
ctx.rule(u'CHAR',u'\x1B')
ctx.rule(u'CHAR',u'\x1C')
ctx.rule(u'CHAR',u'\x1D')
ctx.rule(u'CHAR',u'\x1E')
ctx.rule(u'CHAR',u'\x1F')
ctx.rule(u'CHAR',u'\x20')
ctx.rule(u'CHAR',u'\x21')
ctx.rule(u'CHAR',u'\x23')
ctx.rule(u'CHAR',u'\x24')
ctx.rule(u'CHAR',u'\x25')
ctx.rule(u'CHAR',u'\x26')
ctx.rule(u'CHAR',u'\x2A')
ctx.rule(u'CHAR',u'\x2B')
ctx.rule(u'CHAR',u'\x2C')
ctx.rule(u'CHAR',u'\x2D')
ctx.rule(u'CHAR',u'\x2E')
ctx.rule(u'CHAR',u'\x30')
ctx.rule(u'CHAR',u'\x31')
ctx.rule(u'CHAR',u'\x32')
ctx.rule(u'CHAR',u'\x33')
ctx.rule(u'CHAR',u'\x34')
ctx.rule(u'CHAR',u'\x35')
ctx.rule(u'CHAR',u'\x36')
ctx.rule(u'CHAR',u'\x37')
ctx.rule(u'CHAR',u'\x38')
ctx.rule(u'CHAR',u'\x39')
ctx.rule(u'CHAR',u'\x3A')
ctx.rule(u'CHAR',u'\x3B')
ctx.rule(u'CHAR',u'\x3C')
ctx.rule(u'CHAR',u'\x3D')
ctx.rule(u'CHAR',u'\x3E')
ctx.rule(u'CHAR',u'\x3F')
ctx.rule(u'CHAR',u'\x40')
ctx.rule(u'CHAR',u'\x41')
ctx.rule(u'CHAR',u'\x42')
ctx.rule(u'CHAR',u'\x43')
ctx.rule(u'CHAR',u'\x44')
ctx.rule(u'CHAR',u'\x45')
ctx.rule(u'CHAR',u'\x46')
ctx.rule(u'CHAR',u'\x47')
ctx.rule(u'CHAR',u'\x48')
ctx.rule(u'CHAR',u'\x49')
ctx.rule(u'CHAR',u'\x4A')
ctx.rule(u'CHAR',u'\x4B')
ctx.rule(u'CHAR',u'\x4C')
ctx.rule(u'CHAR',u'\x4D')
ctx.rule(u'CHAR',u'\x4E')
ctx.rule(u'CHAR',u'\x4F')
ctx.rule(u'CHAR',u'\x50')
ctx.rule(u'CHAR',u'\x51')
ctx.rule(u'CHAR',u'\x52')
ctx.rule(u'CHAR',u'\x53')
ctx.rule(u'CHAR',u'\x54')
ctx.rule(u'CHAR',u'\x55')
ctx.rule(u'CHAR',u'\x56')
ctx.rule(u'CHAR',u'\x57')
ctx.rule(u'CHAR',u'\x58')
ctx.rule(u'CHAR',u'\x59')
ctx.rule(u'CHAR',u'\x5A')
ctx.rule(u'CHAR',u'\x5C')
ctx.rule(u'CHAR',u'\x5E')
ctx.rule(u'CHAR',u'\x5F')
ctx.rule(u'CHAR',u'\x61')
ctx.rule(u'CHAR',u'\x62')
ctx.rule(u'CHAR',u'\x63')
ctx.rule(u'CHAR',u'\x64')
ctx.rule(u'CHAR',u'\x65')
ctx.rule(u'CHAR',u'\x66')
ctx.rule(u'CHAR',u'\x67')
ctx.rule(u'CHAR',u'\x68')
ctx.rule(u'CHAR',u'\x69')
ctx.rule(u'CHAR',u'\x6A')
ctx.rule(u'CHAR',u'\x6B')
ctx.rule(u'CHAR',u'\x6C')
ctx.rule(u'CHAR',u'\x6D')
ctx.rule(u'CHAR',u'\x6E')
ctx.rule(u'CHAR',u'\x6F')
ctx.rule(u'CHAR',u'\x70')
ctx.rule(u'CHAR',u'\x71')
ctx.rule(u'CHAR',u'\x72')
ctx.rule(u'CHAR',u'\x73')
ctx.rule(u'CHAR',u'\x74')
ctx.rule(u'CHAR',u'\x75')
ctx.rule(u'CHAR',u'\x76')
ctx.rule(u'CHAR',u'\x77')
ctx.rule(u'CHAR',u'\x78')
ctx.rule(u'CHAR',u'\x79')
ctx.rule(u'CHAR',u'\x7A')
ctx.rule(u'CHAR',u'\x7C')
ctx.rule(u'CHAR',u'\x7E')
ctx.rule(u'CHAR',u'\x7F')
