ctx.rule(u'START', u'{PROGRAM}')

ctx.rule(u'PROGRAM', u'{STATEMENT_LIST}')

ctx.rule(u'STATEMENT_LIST', u'{STATEMENT};\n{STATEMENT_LIST}')
ctx.rule(u'STATEMENT_LIST', u'{STATEMENT}\n')

###

ctx.rule(u'STATEMENT', u'{ASSIGNMENT}')
ctx.rule(u'STATEMENT', u'{EXPRESSION}')
ctx.rule(u'STATEMENT', u'{METHOD_DEF}')
ctx.rule(u'STATEMENT', u'{CONTROL_FLOW}')

ctx.rule(u'ASSIGNMENT', u'{IDENTIFIER} = {EXPRESSION}')

ctx.rule(u'METHOD_DEF', u'def {IDENTIFIER}({PARAM_LIST_OPT})\n{STATEMENT_LIST}{RETURN}\nend')
ctx.rule(u'METHOD_DEF', u'{IDENTIFIER} = lambda \{ |{PARAM_LIST_OPT}|\n{STATEMENT_LIST} \}')
ctx.rule(u'METHOD_DEF', u'{IDENTIFIER} = Proc.new \{ |{PARAM_LIST_OPT}|\n{STATEMENT_LIST} \}')

ctx.rule(u'PARAM_LIST_OPT', u'{PARAM_LIST}')
ctx.rule(u'PARAM_LIST_OPT', u'')

ctx.rule(u'PARAM_LIST', u'{IDENTIFIER}, {PARAM_LIST}')
ctx.rule(u'PARAM_LIST', u'{IDENTIFIER}')

ctx.rule(u'RETURN', u'\nreturn {EXPRESSION}')
ctx.rule(u'RETURN', u'')

ctx.rule(u'CONTROL_FLOW', u'{IF_EXPRESSION}')
ctx.rule(u'CONTROL_FLOW', u'{WHILE_EXPRESSION}')
ctx.rule(u'CONTROL_FLOW', u'{UNLESS_EXPRESSION}')
ctx.rule(u'CONTROL_FLOW', u'{CASE_EXPRESSION}')

ctx.rule(u'CASE_EXPRESSION', u'case {EXPRESSION}\n{WHEN_CLAUSES}else\n{STATEMENT_LIST}end')
ctx.rule(u'WHEN_CLAUSES', u'when {EXPRESSION}\n{STATEMENT_LIST}\n{WHEN_CLAUSES}')
ctx.rule(u'WHEN_CLAUSES', u'when {EXPRESSION}\n{STATEMENT_LIST}')

ctx.rule(u'IF_EXPRESSION', u'if {EXPRESSION} then\n{STATEMENT_LIST}end')
ctx.rule(u'IF_EXPRESSION', u'if {EXPRESSION} then\n{STATEMENT_LIST} else\n{STATEMENT_LIST}end')

ctx.rule(u'WHILE_EXPRESSION', u'while {EXPRESSION}\n{STATEMENT_LIST}end')

ctx.rule(u'UNLESS_EXPRESSION', u'unless {EXPRESSION} then\n{STATEMENT_LIST}end')

###

ctx.rule(u'EXPRESSION', u'{OPERATION}')
ctx.rule(u'EXPRESSION', u'{LITERAL}')
ctx.rule(u'EXPRESSION', u'{METHOD_CALL}')

ctx.rule(u'EXPRESSION_LIST', u'{EXPRESSION}, {EXPRESSION_LIST}')
ctx.rule(u'EXPRESSION_LIST', u'{EXPRESSION}')

ctx.rule(u'OPERATION', u'{EXPRESSION} {OPERATOR} {EXPRESSION}')
ctx.rule(u'OPERATION', u'({EXPRESSION} {LOGIC_OPERATOR} {EXPRESSION})')
ctx.rule(u'OPERATOR', u'+')
ctx.rule(u'OPERATOR', u'-')
ctx.rule(u'OPERATOR', u'*')
ctx.rule(u'OPERATOR', u'/')
ctx.rule(u'OPERATOR', u'%')
ctx.rule(u'LOGIC_OPERATOR', u'==')
ctx.rule(u'LOGIC_OPERATOR', u'!=')
ctx.rule(u'LOGIC_OPERATOR', u'<')
ctx.rule(u'LOGIC_OPERATOR', u'>')
ctx.rule(u'LOGIC_OPERATOR', u'&&')
ctx.rule(u'LOGIC_OPERATOR', u'||')
ctx.rule(u'LOGIC_OPERATOR', u'..')
ctx.rule(u'LOGIC_OPERATOR', u'...')

ctx.rule(u'METHOD_CALL', u'{IDENTIFIER}.call({ARGUMENT_LIST})')
ctx.rule(u'METHOD_CALL', u'{IDENTIFIER}({ARGUMENT_LIST})')
ctx.rule(u'ARGUMENT_LIST', u'{EXPRESSION_LIST}')
ctx.rule(u'ARGUMENT_LIST', u'')

###

ctx.rule(u'LITERAL', u'{NUMBER}')
ctx.rule(u'LITERAL', u'{STRING}')
ctx.rule(u'LITERAL', u'{BOOLEAN}')

ctx.rule(u'NUMBER', u'{DIGITS}')
ctx.rule(u'STRING', u'"{CHARS}"')
ctx.rule(u'BOOLEAN', u'true')
ctx.rule(u'BOOLEAN', u'false')

ctx.rule(u'DIGITS', u'{DIGITS}{DIGIT}')
ctx.rule(u'DIGITS', u'{PDIGIT}')
ctx.rule(u'DIGIT', u'0')
ctx.rule(u'DIGIT', u'1')
ctx.rule(u'DIGIT', u'2')
ctx.rule(u'DIGIT', u'3')
ctx.rule(u'DIGIT', u'4')
ctx.rule(u'DIGIT', u'5')
ctx.rule(u'DIGIT', u'6')
ctx.rule(u'DIGIT', u'7')
ctx.rule(u'DIGIT', u'8')
ctx.rule(u'DIGIT', u'9')
ctx.rule(u'PDIGIT', u'1')
ctx.rule(u'PDIGIT', u'2')
ctx.rule(u'PDIGIT', u'3')
ctx.rule(u'PDIGIT', u'4')
ctx.rule(u'PDIGIT', u'5')
ctx.rule(u'PDIGIT', u'6')
ctx.rule(u'PDIGIT', u'7')
ctx.rule(u'PDIGIT', u'8')
ctx.rule(u'PDIGIT', u'9')

ctx.rule(u'CHARS', u'{CHAR}{CHARS}')
ctx.rule(u'CHARS', u'{CHAR}')
ctx.rule(u'CHAR', u'{LETTER}')
ctx.rule(u'CHAR', u'{DIGIT}')
ctx.rule(u'CHAR', u'{SPECIAL}')

ctx.rule(u'SPECIAL', u' ')
ctx.rule(u'SPECIAL', u'.')
ctx.rule(u'SPECIAL', u'@')
ctx.rule(u'SPECIAL', u'$')
ctx.rule(u'SPECIAL', u'?')
ctx.rule(u'SPECIAL', u'&')
ctx.rule(u'SPECIAL', u'_')

ctx.rule(u'IDENTIFIER', u'id_{LETTER}')

ctx.rule(u'LETTER',u'a')
ctx.rule(u'LETTER',u'b')
ctx.rule(u'LETTER',u'c')
ctx.rule(u'LETTER',u'd')
ctx.rule(u'LETTER',u'e')
ctx.rule(u'LETTER',u'f')
ctx.rule(u'LETTER',u'g')
ctx.rule(u'LETTER',u'h')
ctx.rule(u'LETTER',u'i')
ctx.rule(u'LETTER',u'j')
ctx.rule(u'LETTER',u'k')
ctx.rule(u'LETTER',u'l')
ctx.rule(u'LETTER',u'm')
ctx.rule(u'LETTER',u'n')
ctx.rule(u'LETTER',u'o')
ctx.rule(u'LETTER',u'p')
ctx.rule(u'LETTER',u'q')
ctx.rule(u'LETTER',u'r')
ctx.rule(u'LETTER',u's')
ctx.rule(u'LETTER',u't')
ctx.rule(u'LETTER',u'u')
ctx.rule(u'LETTER',u'v')
ctx.rule(u'LETTER',u'w')
ctx.rule(u'LETTER',u'x')
ctx.rule(u'LETTER',u'y')
ctx.rule(u'LETTER',u'z')
ctx.rule(u'LETTER',u'A')
ctx.rule(u'LETTER',u'B')
ctx.rule(u'LETTER',u'C')
ctx.rule(u'LETTER',u'D')
ctx.rule(u'LETTER',u'E')
ctx.rule(u'LETTER',u'F')
ctx.rule(u'LETTER',u'G')
ctx.rule(u'LETTER',u'H')
ctx.rule(u'LETTER',u'I')
ctx.rule(u'LETTER',u'J')
ctx.rule(u'LETTER',u'K')
ctx.rule(u'LETTER',u'L')
ctx.rule(u'LETTER',u'M')
ctx.rule(u'LETTER',u'N')
ctx.rule(u'LETTER',u'O')
ctx.rule(u'LETTER',u'P')
ctx.rule(u'LETTER',u'Q')
ctx.rule(u'LETTER',u'R')
ctx.rule(u'LETTER',u'S')
ctx.rule(u'LETTER',u'T')
ctx.rule(u'LETTER',u'U')
ctx.rule(u'LETTER',u'V')
ctx.rule(u'LETTER',u'W')
ctx.rule(u'LETTER',u'X')
ctx.rule(u'LETTER',u'Y')
ctx.rule(u'LETTER',u'Z')
